# Generated by Django 5.2.3 on 2025-11-17 16:41

import clientsetup.models
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('setup', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Floor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('number', models.CharField(max_length=20)),
                ('total_units', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('ACTIVE', 'Active'), ('LOCKED', 'Locked'), ('ARCHIVED', 'Archived')], default='DRAFT', max_length=16)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['tower__name', 'number'],
            },
        ),
        migrations.CreateModel(
            name='Bank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=150)),
                ('bank_category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='setup.bankcategory')),
                ('bank_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='setup.banktype')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BankBranch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('branch_name', models.CharField(max_length=150)),
                ('branch_code', models.CharField(blank=True, max_length=50)),
                ('ifsc', models.CharField(max_length=11, unique=True, validators=[django.core.validators.RegexValidator('^[A-Z]{4}0[0-9A-Z]{6}$', 'Invalid IFSC format. Expected like HDFC0001234')])),
                ('micr', models.CharField(blank=True, max_length=20)),
                ('address', models.TextField(blank=True)),
                ('contact_name', models.CharField(blank=True, max_length=120)),
                ('contact_phone', models.CharField(blank=True, max_length=32)),
                ('contact_email', models.EmailField(blank=True, max_length=254)),
                ('bank', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='branches', to='clientsetup.bank')),
            ],
            options={
                'unique_together': {('bank', 'branch_name')},
            },
        ),
        migrations.CreateModel(
            name='FloorDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('file', models.FileField(upload_to='floor_docs/')),
                ('floor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='clientsetup.floor')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=30, unique=True)),
                ('notif_type', models.CharField(choices=[('SYSTEM', 'System'), ('MANUAL', 'Manual')], default='SYSTEM', max_length=10)),
                ('message', models.TextField()),
                ('priority', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High')], default='MEDIUM', max_length=6)),
                ('delivery_method', models.CharField(choices=[('EMAIL', 'Email'), ('SMS', 'SMS'), ('PUSH', 'Push'), ('IN_APP', 'In-app')], default='EMAIL', max_length=10)),
                ('scheduled_at', models.DateTimeField(blank=True, null=True)),
                ('expires_on', models.DateField(blank=True, null=True)),
                ('read_status', models.CharField(choices=[('UNREAD', 'Unread'), ('READ', 'Read')], default='UNREAD', max_length=6)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive')], default='ACTIVE', max_length=8)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='NotificationDispatchLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('attempt_no', models.PositiveIntegerField(default=1)),
                ('channel', models.CharField(choices=[('EMAIL', 'Email'), ('SMS', 'SMS'), ('PUSH', 'Push'), ('IN_APP', 'In-app')], max_length=10)),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('success', models.BooleanField(default=False)),
                ('response_meta', models.JSONField(blank=True, null=True)),
                ('notification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dispatch_logs', to='clientsetup.notification')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('location', models.CharField(blank=True, max_length=255)),
                ('developer', models.CharField(blank=True, max_length=200)),
                ('rera_no', models.CharField(blank=True, max_length=50, unique=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('possession_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('APPROVAL_PENDING', 'Approval Pending'), ('APPROVED', 'Approved'), ('UNDER_CONSTRUCTION', 'Under Construction'), ('READY_TO_MOVE', 'Ready to Move'), ('ON_HOLD', 'On Hold'), ('CANCELLED', 'Cancelled'), ('CLOSED', 'Closed')], default='DRAFT', max_length=32)),
                ('approval_status', models.CharField(choices=[('NOT_REQUIRED', 'Not Required'), ('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('REVOKED', 'Revoked')], default='PENDING', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('belongs_to', models.ForeignKey(help_text='Owning ADMIN user', on_delete=django.db.models.deletion.PROTECT, related_name='owned_projects', to=settings.AUTH_USER_MODEL)),
                ('project_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='setup.projecttype')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='PaymentPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(help_text='e.g., PPL001', max_length=30, unique=True)),
                ('name', models.CharField(max_length=150)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_plans', to='clientsetup.project')),
            ],
            options={
                'ordering': ['project__name', 'name'],
            },
        ),
        migrations.AddField(
            model_name='notification',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to='clientsetup.project'),
        ),
        migrations.CreateModel(
            name='ProjectBank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('apf_number', models.CharField(blank=True, max_length=100)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive')], default='ACTIVE', max_length=10)),
                ('bank_branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='project_banks', to='clientsetup.bankbranch')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_banks', to='clientsetup.project')),
            ],
        ),
        migrations.CreateModel(
            name='ProjectBankProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='setup.loanproduct')),
                ('project_bank', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='clientsetup.projectbank')),
            ],
        ),
        migrations.CreateModel(
            name='Tower',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('total_floors', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('ACTIVE', 'Active'), ('LOCKED', 'Locked'), ('ARCHIVED', 'Archived')], default='DRAFT', max_length=16)),
                ('notes', models.TextField(blank=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='towers', to='clientsetup.project')),
                ('tower_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='setup.towertype')),
            ],
            options={
                'ordering': ['project__name', 'name'],
            },
        ),
        migrations.CreateModel(
            name='MilestonePlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=150)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('calc_mode', models.CharField(choices=[('PERCENTAGE', 'Percentage'), ('AMOUNT', 'Amount')], default='PERCENTAGE', max_length=12)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('enable_pg_integration', models.BooleanField(default=False)),
                ('verified_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('ACTIVE', 'Active'), ('LOCKED', 'Locked'), ('ARCHIVED', 'Archived')], default='DRAFT', max_length=12)),
                ('notes', models.TextField(blank=True)),
                ('responsible_user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='responsible_plans', to=settings.AUTH_USER_MODEL)),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_plans', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='milestone_plans', to='clientsetup.project')),
                ('tower', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='milestone_plans', to='clientsetup.tower')),
            ],
            options={
                'ordering': ['project__name', 'name'],
            },
        ),
        migrations.AddField(
            model_name='floor',
            name='tower',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='floors', to='clientsetup.tower'),
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('unit_no', models.CharField(max_length=50)),
                ('carpet_sqft', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('builtup_sqft', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('rera_sqft', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('agreement_value', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('construction_start', models.DateField(blank=True, null=True)),
                ('completion_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('NOT_RELEASED', 'Not Released'), ('AVAILABLE', 'Available'), ('HOLD', 'Hold'), ('BOOKED', 'Booked'), ('SOLD', 'Sold'), ('CANCELLED', 'Cancelled'), ('BLOCKED', 'Blocked')], default='NOT_RELEASED', max_length=16)),
                ('notes', models.TextField(blank=True)),
                ('facing', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='setup.facing')),
                ('floor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='units', to='clientsetup.floor')),
                ('parking_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='setup.parkingtype')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='units', to='clientsetup.project')),
                ('tower', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='units', to='clientsetup.tower')),
                ('unit_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='setup.unittype')),
            ],
        ),
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('carpet_sqft', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('builtup_sqft', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('rera_area_sqft', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='RERA Area (sq.ft)')),
                ('saleable_sqft', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Saleable Area (Sq.ft)')),
                ('other_area_sqft', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Other Area (Sq.ft)')),
                ('loft_area_sqft', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Loft Area (Sq.ft)')),
                ('base_price_psf', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Base Price (per sq.ft)')),
                ('rate_psf', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Rate (per sq.ft)')),
                ('agreement_value', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, verbose_name='Agreement Value')),
                ('gst_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='GST Amount')),
                ('development_infra_charge', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Development/Infra Charge')),
                ('stamp_duty_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Stamp Duty Amount')),
                ('registration_charges', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Registration Charges')),
                ('legal_fee', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Legal Fee')),
                ('total_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, verbose_name='Total Cost')),
                ('unit_status', models.CharField(choices=[('NOT_RELEASED', 'Not Released'), ('AVAILABLE', 'Available'), ('HOLD', 'Hold'), ('BOOKED', 'Booked'), ('SOLD', 'Sold'), ('CANCELLED', 'Cancelled'), ('BLOCKED', 'Blocked')], default='NOT_RELEASED', max_length=16)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('ACTIVE', 'Active'), ('INACTIVE', 'Inactive')], default='DRAFT', max_length=12)),
                ('availability_status', models.CharField(choices=[('AVAILABLE', 'Available'), ('BOOKED', 'Booked'), ('BLOCKED', 'Blocked')], default='AVAILABLE', help_text='Business-facing availability: Available / Booked / Blocked', max_length=9, verbose_name='Inventory Availability')),
                ('block_period_days', models.PositiveIntegerField(blank=True, null=True, verbose_name='Block Period (days)')),
                ('registration_number', models.CharField(blank=True, max_length=64, verbose_name='Registration Number')),
                ('description', models.TextField(blank=True, verbose_name='Inventory Description')),
                ('photo', models.ImageField(blank=True, null=True, upload_to=clientsetup.models.inventory_photo_upload_to)),
                ('configuration', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='setup.unitconfiguration')),
                ('facing', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='setup.facing')),
                ('floor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventories', to='clientsetup.floor')),
                ('unit_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='setup.unittype')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inventories', to='clientsetup.project')),
                ('tower', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventories', to='clientsetup.tower')),
                ('unit', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventory_items', to='clientsetup.unit')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='InventoryDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('doc_type', models.CharField(choices=[('FLOOR_PLAN', 'Floor Plan'), ('OTHER', 'Other'), ('PROJECT_PLAN', 'Project Plan')], max_length=20)),
                ('file', models.FileField(upload_to=clientsetup.models.inventory_doc_upload_to)),
                ('original_name', models.CharField(blank=True, max_length=255)),
                ('inventory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='clientsetup.inventory')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['inventory', 'doc_type'], name='clientsetup_invento_9c673e_idx')],
            },
        ),
        migrations.CreateModel(
            name='MilestoneSlab',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order_index', models.PositiveIntegerField(default=1)),
                ('name', models.CharField(max_length=120)),
                ('percentage', models.DecimalField(blank=True, decimal_places=3, max_digits=6, null=True)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('remarks', models.CharField(blank=True, max_length=255)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slabs', to='clientsetup.milestoneplan')),
            ],
            options={
                'ordering': ['order_index'],
                'unique_together': {('plan', 'order_index')},
            },
        ),
        migrations.CreateModel(
            name='PaymentSlab',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order_index', models.PositiveIntegerField(default=1)),
                ('name', models.CharField(max_length=120)),
                ('percentage', models.DecimalField(decimal_places=3, max_digits=6)),
                ('days', models.PositiveIntegerField(blank=True, help_text='Days from booking/agreement etc.', null=True)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slabs', to='clientsetup.paymentplan')),
            ],
            options={
                'ordering': ['order_index'],
                'unique_together': {('plan', 'order_index')},
            },
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['status'], name='clientsetup_status_3ccfd0_idx'),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['approval_status'], name='clientsetup_approva_021a1c_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='paymentplan',
            unique_together={('project', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='projectbank',
            unique_together={('project', 'bank_branch')},
        ),
        migrations.AlterUniqueTogether(
            name='projectbankproduct',
            unique_together={('project_bank', 'product')},
        ),
        migrations.AlterUniqueTogether(
            name='tower',
            unique_together={('project', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='milestoneplan',
            unique_together={('project', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='floor',
            unique_together={('tower', 'number')},
        ),
        migrations.AddIndex(
            model_name='unit',
            index=models.Index(fields=['project', 'status'], name='clientsetup_project_8f9493_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='unit',
            unique_together={('floor', 'unit_no')},
        ),
        migrations.AddIndex(
            model_name='inventory',
            index=models.Index(fields=['project', 'tower', 'status'], name='clientsetup_project_805021_idx'),
        ),
        migrations.AddIndex(
            model_name='inventory',
            index=models.Index(fields=['unit_status'], name='clientsetup_unit_st_b66768_idx'),
        ),
        migrations.AddIndex(
            model_name='inventory',
            index=models.Index(fields=['availability_status'], name='clientsetup_availab_be403a_idx'),
        ),
    ]
