# Generated by Django 5.2.3 on 2025-11-20 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientsetup', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='price_per_sqft',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Base price per square foot for this project', max_digits=12, null=True),
        ),
    ]
