# Generated by Django 5.2.3 on 2025-11-21 07:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('channel', '0005_partnertier_admin_partnertier_commission_amount_and_more'),
        ('clientsetup', '0002_project_price_per_sqft'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CommercialOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=150)),
                ('code', models.CharField(blank=True, max_length=50)),
                ('description', models.TextField(blank=True)),
                ('target_type', models.CharField(choices=[('CUSTOMER', 'Customer'), ('CHANNEL_PARTNER', 'Channel Partner')], default='CUSTOMER', max_length=20)),
                ('value_type', models.CharField(choices=[('AMOUNT', 'Flat Amount'), ('PERCENTAGE', 'Percentage'), ('GIFT', 'Gift / Non-monetary')], default='AMOUNT', max_length=20)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, help_text='Flat amount discount / benefit', max_digits=14, null=True)),
                ('percentage', models.DecimalField(blank=True, decimal_places=2, help_text='Percentage discount (e.g. 5.00 = 5%)', max_digits=5, null=True)),
                ('gift_description', models.CharField(blank=True, help_text="Eg. 'Free Car', 'Modular Kitchen', etc.", max_length=255)),
                ('min_booking_amount', models.DecimalField(blank=True, decimal_places=2, help_text='Minimum agreement / deal value required (optional)', max_digits=14, null=True)),
                ('valid_from', models.DateField(blank=True, null=True)),
                ('valid_till', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('admin', models.ForeignKey(help_text='Admin who owns this offer scheme', on_delete=django.db.models.deletion.CASCADE, related_name='offers_created', to=settings.AUTH_USER_MODEL)),
                ('cp_tier', models.ForeignKey(blank=True, help_text='Required when target_type=CHANNEL_PARTNER', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='offers', to='channel.partnertier')),
                ('project', models.ForeignKey(blank=True, help_text='Null = all projects of this admin', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='offers', to='clientsetup.project')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['admin', 'target_type', 'is_active'], name='clientsetup_admin_i_caa49b_idx'), models.Index(fields=['project'], name='clientsetup_project_b356bc_idx'), models.Index(fields=['valid_till'], name='clientsetup_valid_t_65ae09_idx')],
            },
        ),
    ]
