# Generated by Django 5.2.3 on 2025-11-29 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientsetup', '0004_inventory_blocked_until_notification_content_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='at_lead_time_email',
            field=models.BooleanField(default=True),
        ),
    ]
