# Generated by Django 5.2.3 on 2025-11-29 17:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientsetup', '0005_project_at_lead_time_email'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ParkingInventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('slot_label', models.CharField(help_text='Slot number / label (e.g. B1-12, P2-45)', max_length=50)),
                ('parking_type', models.CharField(choices=[('OPEN', 'Open'), ('COVERED', 'Covered'), ('STILT', 'Stilt'), ('PODIUM', 'Podium'), ('OTHER', 'Other')], default='OPEN', max_length=10)),
                ('level_label', models.CharField(blank=True, help_text='Basement-1 / Podium-2 / Ground / Stilt, etc.', max_length=50)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('ACTIVE', 'Active'), ('INACTIVE', 'Inactive')], default='DRAFT', help_text='Parking master status (Draft/Active/Inactive)', max_length=12)),
                ('availability_status', models.CharField(choices=[('AVAILABLE', 'Available'), ('BOOKED', 'Booked'), ('BLOCKED', 'Blocked')], default='AVAILABLE', help_text='Available / Booked / Blocked', max_length=9)),
                ('blocked_until', models.DateTimeField(blank=True, help_text='When block period ends. After this slot can be made AVAILABLE again.', null=True)),
                ('remarks', models.TextField(blank=True)),
                ('project', models.ForeignKey(help_text='Project to which this parking belongs', on_delete=django.db.models.deletion.CASCADE, related_name='parking_inventories', to='clientsetup.project')),
                ('reserved_for_unit', models.ForeignKey(blank=True, help_text='If this slot is reserved for a particular unit / flat', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reserved_parkings', to='clientsetup.unit')),
                ('tower', models.ForeignKey(blank=True, help_text='Optional – if parking tower-wise segregated hai', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='parking_inventories', to='clientsetup.tower')),
            ],
            options={
                'ordering': ['project_id', 'slot_label'],
            },
        ),
        migrations.CreateModel(
            name='ParkingStatusHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('old_availability', models.CharField(choices=[('AVAILABLE', 'Available'), ('BOOKED', 'Booked'), ('BLOCKED', 'Blocked')], max_length=9)),
                ('new_availability', models.CharField(choices=[('AVAILABLE', 'Available'), ('BOOKED', 'Booked'), ('BLOCKED', 'Blocked')], max_length=9)),
                ('reason', models.CharField(blank=True, max_length=255)),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('parking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='clientsetup.parkinginventory')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='parkinginventory',
            index=models.Index(fields=['project', 'availability_status'], name='clientsetup_project_fa72a3_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='parkinginventory',
            unique_together={('project', 'slot_label')},
        ),
    ]
