# Generated by Django 5.2.3 on 2025-11-29 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientsetup', '0006_parkinginventory_parkingstatushistory_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='parkinginventory',
            name='area_sqft',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Parking Area (sq.ft)'),
        ),
        migrations.AddField(
            model_name='parkinginventory',
            name='rera_slot_no',
            field=models.CharField(blank=True, help_text='Parking slot number as per RERA-sanctioned layout.', max_length=100, verbose_name='RERA Parking No.'),
        ),
        migrations.AlterField(
            model_name='parkinginventory',
            name='slot_label',
            field=models.CharField(help_text='Internal slot label (e.g. B1-12, P2-45).', max_length=50),
        ),
    ]
