# Generated by Django 5.2.3 on 2025-11-29 19:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientsetup', '0007_parkinginventory_area_sqft_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='parkinginventory',
            name='block_label',
            field=models.CharField(blank=True, help_text='Block / Row / Zone label (e.g. A, B1, C-Wing)', max_length=20),
        ),
        migrations.AddField(
            model_name='parkinginventory',
            name='floor',
            field=models.ForeignKey(blank=True, help_text='Optional – exact parking level (Basement-1 / Podium-2 etc.)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='parking_inventories', to='clientsetup.floor'),
        ),
        migrations.AddField(
            model_name='parkinginventory',
            name='is_accessible',
            field=models.BooleanField(default=False, help_text='Accessible / wider slot (specially-abled etc.)?'),
        ),
        migrations.AddField(
            model_name='parkinginventory',
            name='is_ev_ready',
            field=models.BooleanField(default=False, help_text='EV charging point available at this slot?'),
        ),
        migrations.AddField(
            model_name='parkinginventory',
            name='rera_parking_type',
            field=models.CharField(blank=True, help_text='e.g. Covered / Open as per RERA, if different from internal type', max_length=50, verbose_name='RERA Parking Type'),
        ),
        migrations.AddField(
            model_name='parkinginventory',
            name='slot_number',
            field=models.CharField(blank=True, help_text='Running number within block (e.g. 53)', max_length=20),
        ),
        migrations.AddField(
            model_name='parkinginventory',
            name='usage_type',
            field=models.CharField(choices=[('RESIDENT', 'Resident'), ('VISITOR', 'Visitor'), ('STAFF', 'Staff'), ('COMMERCIAL', 'Commercial')], default='RESIDENT', help_text='Resident / Visitor / Staff / Commercial', max_length=16),
        ),
        migrations.AddField(
            model_name='parkinginventory',
            name='vehicle_type',
            field=models.CharField(choices=[('TWO_WHEELER', 'Two wheeler'), ('FOUR_WHEELER', 'Four wheeler'), ('BOTH', 'Both')], default='FOUR_WHEELER', help_text='Two wheeler / Four wheeler / Both', max_length=16),
        ),
        migrations.AlterField(
            model_name='parkinginventory',
            name='area_sqft',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Approx. area of the parking slot (for documentation / costing)', max_digits=10, null=True, verbose_name='Parking Area (sq.ft)'),
        ),
        migrations.AlterField(
            model_name='parkinginventory',
            name='level_label',
            field=models.CharField(blank=True, help_text='Text label for level – Basement-1 / Podium-2 / Ground etc.', max_length=50),
        ),
        migrations.AlterField(
            model_name='parkinginventory',
            name='rera_slot_no',
            field=models.CharField(blank=True, help_text='Parking slot number as per RERA-approved plan', max_length=50, verbose_name='RERA Slot No.'),
        ),
        migrations.AlterField(
            model_name='parkinginventory',
            name='slot_label',
            field=models.CharField(help_text='Full slot label as seen on paper (e.g. A53, B1-12, P2-45)', max_length=50),
        ),
        migrations.AddIndex(
            model_name='parkinginventory',
            index=models.Index(fields=['project', 'vehicle_type', 'usage_type'], name='clientsetup_project_5e9df2_idx'),
        ),
    ]
