# Generated by Django 5.2.3 on 2025-12-02 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientsetup', '0008_parkinginventory_block_label_parkinginventory_floor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='price_per_parking',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Base price per parking for this project', max_digits=12, null=True),
        ),
    ]
