# Generated by Django 5.2.3 on 2025-12-05 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientsetup', '0009_project_price_per_parking'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='is_pricing_balcony_carpert',
            field=models.BooleanField(default=True),
        ),
    ]
