# Generated by Django 5.2.3 on 2025-12-06 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientsetup', '0010_project_is_pricing_balcony_carpert'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory',
            name='balcony_area_sqft',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Balcony Area (Sq.ft)'),
        ),
    ]
