# Generated by Django 5.2.3 on 2025-12-06 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientsetup', '0011_inventory_balcony_area_sqft'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory',
            name='approved_limit_price_psf',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Lowest rate sales team is allowed to go till (management approved)', max_digits=12, null=True, verbose_name='Approved Limit Price (per sq.ft)'),
        ),
        migrations.AddField(
            model_name='inventory',
            name='core_base_price_psf',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Original/base rate before any approvals or discounts', max_digits=12, null=True, verbose_name='Core Base Price (per sq.ft)'),
        ),
        migrations.AddField(
            model_name='inventory',
            name='customer_base_price_psf',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Rate currently being offered/pitched to customer for this unit', max_digits=12, null=True, verbose_name='Customer Base Price (per sq.ft)'),
        ),
    ]
