# Generated by Django 5.2.3 on 2025-12-08 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientsetup', '0012_inventory_approved_limit_price_psf_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='reminder_offsets_minutes',
            field=models.JSONField(blank=True, default=list, help_text='List of reminder times in minutes before event date. Example: [1440, 60, 30] → 1 day, 1 hour, 30 minutes before.'),
        ),
    ]
