# Generated by Django 5.2.3 on 2025-12-11 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientsetup', '0013_project_reminder_offsets_minutes'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='office_address',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
