# Generated by Django 5.2.3 on 2025-11-17 16:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BankCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('code', models.CharField(db_index=True, help_text='Stable programmatic code, e.g. RESIDENTIAL, MIXED_USE', max_length=50, unique=True, validators=[django.core.validators.RegexValidator('^[A-Z0-9_]+$', 'Use only A–Z, 0–9 and _')])),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['name'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BankType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('code', models.CharField(db_index=True, help_text='Stable programmatic code, e.g. RESIDENTIAL, MIXED_USE', max_length=50, unique=True, validators=[django.core.validators.RegexValidator('^[A-Z0-9_]+$', 'Use only A–Z, 0–9 and _')])),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['name'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Designation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('code', models.CharField(db_index=True, help_text='Stable programmatic code, e.g. RESIDENTIAL, MIXED_USE', max_length=50, unique=True, validators=[django.core.validators.RegexValidator('^[A-Z0-9_]+$', 'Use only A–Z, 0–9 and _')])),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['name'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Facing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('code', models.CharField(db_index=True, help_text='Stable programmatic code, e.g. RESIDENTIAL, MIXED_USE', max_length=50, unique=True, validators=[django.core.validators.RegexValidator('^[A-Z0-9_]+$', 'Use only A–Z, 0–9 and _')])),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['name'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FamilySize',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('code', models.CharField(db_index=True, help_text='Stable programmatic code, e.g. RESIDENTIAL, MIXED_USE', max_length=50, unique=True, validators=[django.core.validators.RegexValidator('^[A-Z0-9_]+$', 'Use only A–Z, 0–9 and _')])),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['name'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LoanProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('code', models.CharField(db_index=True, help_text='Stable programmatic code, e.g. RESIDENTIAL, MIXED_USE', max_length=50, unique=True, validators=[django.core.validators.RegexValidator('^[A-Z0-9_]+$', 'Use only A–Z, 0–9 and _')])),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['name'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MilestoneStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('code', models.CharField(db_index=True, help_text='Stable programmatic code, e.g. RESIDENTIAL, MIXED_USE', max_length=50, unique=True, validators=[django.core.validators.RegexValidator('^[A-Z0-9_]+$', 'Use only A–Z, 0–9 and _')])),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['name'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Occupation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('code', models.CharField(db_index=True, help_text='Stable programmatic code, e.g. RESIDENTIAL, MIXED_USE', max_length=50, unique=True, validators=[django.core.validators.RegexValidator('^[A-Z0-9_]+$', 'Use only A–Z, 0–9 and _')])),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['name'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='OfferingType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('code', models.CharField(db_index=True, help_text='Stable programmatic code, e.g. RESIDENTIAL, MIXED_USE', max_length=50, unique=True, validators=[django.core.validators.RegexValidator('^[A-Z0-9_]+$', 'Use only A–Z, 0–9 and _')])),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['name'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ParkingType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('code', models.CharField(db_index=True, help_text='Stable programmatic code, e.g. RESIDENTIAL, MIXED_USE', max_length=50, unique=True, validators=[django.core.validators.RegexValidator('^[A-Z0-9_]+$', 'Use only A–Z, 0–9 and _')])),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['name'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PossienDesigned',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('code', models.CharField(db_index=True, help_text='Stable programmatic code, e.g. RESIDENTIAL, MIXED_USE', max_length=50, unique=True, validators=[django.core.validators.RegexValidator('^[A-Z0-9_]+$', 'Use only A–Z, 0–9 and _')])),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['name'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ProjectType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('code', models.CharField(db_index=True, help_text='Stable programmatic code, e.g. RESIDENTIAL, MIXED_USE', max_length=50, unique=True, validators=[django.core.validators.RegexValidator('^[A-Z0-9_]+$', 'Use only A–Z, 0–9 and _')])),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['name'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ResidencyOwnerShip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('code', models.CharField(db_index=True, help_text='Stable programmatic code, e.g. RESIDENTIAL, MIXED_USE', max_length=50, unique=True, validators=[django.core.validators.RegexValidator('^[A-Z0-9_]+$', 'Use only A–Z, 0–9 and _')])),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['name'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TowerType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('code', models.CharField(db_index=True, help_text='Stable programmatic code, e.g. RESIDENTIAL, MIXED_USE', max_length=50, unique=True, validators=[django.core.validators.RegexValidator('^[A-Z0-9_]+$', 'Use only A–Z, 0–9 and _')])),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['name'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='UnitConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('code', models.CharField(db_index=True, help_text='Stable programmatic code, e.g. RESIDENTIAL, MIXED_USE', max_length=50, unique=True, validators=[django.core.validators.RegexValidator('^[A-Z0-9_]+$', 'Use only A–Z, 0–9 and _')])),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['name'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='UnitType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('code', models.CharField(db_index=True, help_text='Stable programmatic code, e.g. RESIDENTIAL, MIXED_USE', max_length=50, unique=True, validators=[django.core.validators.RegexValidator('^[A-Z0-9_]+$', 'Use only A–Z, 0–9 and _')])),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['name'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='VisitingHalf',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('code', models.CharField(db_index=True, help_text='Stable programmatic code, e.g. RESIDENTIAL, MIXED_USE', max_length=50, unique=True, validators=[django.core.validators.RegexValidator('^[A-Z0-9_]+$', 'Use only A–Z, 0–9 and _')])),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['name'],
                'abstract': False,
            },
        ),
    ]
