# Generated by Django 5.2.3 on 2025-12-05 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_user_email_loginotp'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='signature',
            field=models.ImageField(blank=True, help_text='Scanned/drawn signature image (PNG/JPEG).', null=True, upload_to='user_signatures/'),
        ),
    ]
