# Generated by Django 5.2.3 on 2025-12-08 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_user_signature'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(blank=True, choices=[('SUPER_ADMIN', 'Super Admin'), ('ADMIN', 'Admin'), ('RECEPTION', 'Reception'), ('CHANNEL_PARTNER', 'Channel Partner'), ('SALES', 'SalesPerson'), ('CALLING_TEAM', 'Calling Team'), ('KYC_TEAM', 'KYC Team')], default='SALES', help_text='Business role', max_length=20, null=True),
        ),
    ]
