# Generated by Django 5.2.3 on 2025-12-11 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientbrand',
            name='accent_color',
            field=models.CharField(default='#2563EB', help_text='Accent color for links, highlights, chips, etc.', max_length=7),
        ),
        migrations.AddField(
            model_name='clientbrand',
            name='background_color',
            field=models.CharField(default='#F5F5F7', help_text='Default page background color.', max_length=7),
        ),
        migrations.AddField(
            model_name='clientbrand',
            name='base_font_size',
            field=models.PositiveSmallIntegerField(default=14, help_text='Base font size in px (e.g. 14, 16).'),
        ),
        migrations.AddField(
            model_name='clientbrand',
            name='button_primary_bg',
            field=models.CharField(default='#102A54', help_text='Primary button background and navbar button background.', max_length=7),
        ),
        migrations.AddField(
            model_name='clientbrand',
            name='button_primary_text',
            field=models.CharField(default='#FFFFFF', help_text='Primary button and navbar text color.', max_length=7),
        ),
        migrations.AddField(
            model_name='clientbrand',
            name='font_family',
            field=models.CharField(default='Inter', help_text="CSS font-family value, e.g. 'Inter', 'Poppins', 'system-ui'.", max_length=100),
        ),
        migrations.AddField(
            model_name='clientbrand',
            name='heading_color',
            field=models.CharField(default='#111827', help_text='Default heading/title color.', max_length=7),
        ),
        migrations.AddField(
            model_name='clientbrand',
            name='is_active',
            field=models.BooleanField(default=True, help_text='If false, this brand is disabled for the client.'),
        ),
        migrations.AlterField(
            model_name='clientbrand',
            name='primary_color',
            field=models.CharField(default='#102A54', help_text='Primary brand color (navbar/footer, primary surfaces).', max_length=7),
        ),
        migrations.AlterField(
            model_name='clientbrand',
            name='secondary_color',
            field=models.CharField(default='#FFFFFF', help_text='Secondary brand color (e.g. text on primary surfaces).', max_length=7),
        ),
    ]
