# Generated by Django 5.2.3 on 2025-12-11 05:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_clientbrand_accent_color_and_more'),
        ('clientsetup', '0013_project_reminder_offsets_minutes'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectUserAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('can_view', models.BooleanField(default=True)),
                ('can_edit', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_accesses', to='clientsetup.project')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_accesses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Project User Access',
                'verbose_name_plural': 'Project User Accesses',
                'unique_together': {('user', 'project')},
            },
        ),
    ]
