# Generated by Django 5.2.3 on 2025-12-16 06:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_projectuseraccess'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='admin',
            field=models.ForeignKey(blank=True, help_text='Owning Admin / Manager', limit_choices_to={'role__in': ['ADMIN', 'MANAGER']}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='team_members', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='user',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_users', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('SUPER_ADMIN', 'Super Admin'), ('ADMIN', 'Admin'), ('MANAGER', 'Manager'), ('RECEPTION', 'Reception'), ('CHANNEL_PARTNER', 'Channel Partner'), ('SALES', 'SalesPerson'), ('CALLING_TEAM', 'Calling Team'), ('KYC_TEAM', 'KYC Team')], default='SALES', max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='signature',
            field=models.ImageField(blank=True, null=True, upload_to='user_signatures/'),
        ),
    ]
