# Generated by Django 5.2.3 on 2025-12-16 07:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_alter_user_admin_alter_user_created_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='admin',
            field=models.ForeignKey(blank=True, help_text='Owning admin for RECEPTION/SALES/CP', limit_choices_to={'role': 'ADMIN'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='team_members', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='user',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='Who created this user', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_users', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(blank=True, choices=[('SUPER_ADMIN', 'Super Admin'), ('ADMIN', 'Admin'), ('RECEPTION', 'Reception'), ('CHANNEL_PARTNER', 'Channel Partner'), ('SALES', 'SalesPerson'), ('CALLING_TEAM', 'Calling Team'), ('KYC_TEAM', 'KYC Team')], default='SALES', help_text='Business role', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='signature',
            field=models.ImageField(blank=True, help_text='Scanned/drawn signature image (PNG/JPEG).', null=True, upload_to='user_signatures/'),
        ),
    ]
