# Generated by Django 5.2.3 on 2025-12-24 12:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_alter_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectuseraccess',
            name='manager',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'MANAGER'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_project_accesses', to=settings.AUTH_USER_MODEL),
        ),
    ]
