# Generated by Django 5.2.3 on 2025-12-24 09:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_projectuseraccess_manager'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectuseraccess',
            name='reports_to',
        ),
    ]
