# Generated by Django 5.2.3 on 2025-11-17 16:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientsetup', '0001_initial'),
        ('salelead', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('form_ref_no', models.CharField(help_text='External form reference / booking form number', max_length=50, unique=True)),
                ('booking_date', models.DateField()),
                ('office_address', models.TextField(blank=True)),
                ('primary_title', models.CharField(blank=True, help_text='Mr / Ms / Mrs / Dr, etc.', max_length=10)),
                ('primary_full_name', models.CharField(max_length=200)),
                ('primary_email', models.EmailField(blank=True, max_length=254)),
                ('primary_mobile_number', models.CharField(blank=True, max_length=32)),
                ('email_2', models.EmailField(blank=True, max_length=254)),
                ('phone_2', models.CharField(blank=True, max_length=32)),
                ('permanent_address', models.TextField(blank=True)),
                ('correspondence_address', models.TextField(blank=True)),
                ('preferred_correspondence', models.CharField(choices=[('PERMANENT', 'Permanent Address'), ('CORRESPONDENCE', 'Correspondence Address')], default='PERMANENT', max_length=16)),
                ('residential_status', models.CharField(blank=True, help_text='Owned / Rented / Company Provided, etc.', max_length=32)),
                ('super_builtup_sqft', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('carpet_sqft', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('balcony_sqft', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('agreement_value', models.DecimalField(decimal_places=2, help_text='Final agreement value for this booking (snapshot)', max_digits=14)),
                ('agreement_value_words', models.CharField(blank=True, help_text='Agreement value in words, for printing', max_length=500)),
                ('agreement_done', models.BooleanField(default=False)),
                ('parking_required', models.BooleanField(default=False)),
                ('parking_details', models.CharField(blank=True, max_length=255)),
                ('parking_number', models.CharField(blank=True, max_length=50)),
                ('gst_no', models.CharField(blank=True, max_length=20)),
                ('kyc_status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=12)),
                ('kyc_deal_amount', models.DecimalField(blank=True, decimal_places=2, help_text='Deal amount sent to client for KYC approval.', max_digits=14, null=True)),
                ('kyc_submitted_at', models.DateTimeField(blank=True, null=True)),
                ('kyc_approved_at', models.DateTimeField(blank=True, null=True)),
                ('payment_plan_type', models.CharField(choices=[('MASTER', 'Project Plan'), ('CUSTOM', 'Custom (per booking)')], default='MASTER', max_length=12)),
                ('custom_payment_plan', models.JSONField(blank=True, help_text="Custom plan only for this booking (shown in 'Make Your Own')", null=True)),
                ('loan_required', models.BooleanField(default=False)),
                ('loan_bank_name', models.CharField(blank=True, max_length=150)),
                ('loan_amount_expected', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('booking_amount', models.DecimalField(decimal_places=2, default=0, help_text='Booking amount taken now', max_digits=14)),
                ('other_charges', models.DecimalField(decimal_places=2, default=0, help_text='Any other charges collected as advance', max_digits=14)),
                ('total_advance', models.DecimalField(decimal_places=2, default=0, help_text='booking_amount + other_charges', max_digits=14)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('BLOCKED', 'Blocked'), ('BOOKED', 'Booked'), ('CANCELLED', 'Cancelled')], default='DRAFT', max_length=16)),
                ('blocked_at', models.DateTimeField(blank=True, null=True)),
                ('booked_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_reason', models.TextField(blank=True)),
                ('channel_partner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookings', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookings_created', to=settings.AUTH_USER_MODEL)),
                ('floor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='bookings', to='clientsetup.floor')),
                ('kyc_approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookings_kyc_approved', to=settings.AUTH_USER_MODEL)),
                ('payment_plan', models.ForeignKey(blank=True, help_text='Only when payment_plan_type=MASTER', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookings', to='clientsetup.paymentplan')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bookings', to='clientsetup.project')),
                ('sales_lead', models.ForeignKey(blank=True, help_text='Source SalesLead, if any', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookings', to='salelead.saleslead')),
                ('tower', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='bookings', to='clientsetup.tower')),
                ('unit', models.ForeignKey(help_text='Flat / Unit being booked or blocked', on_delete=django.db.models.deletion.PROTECT, related_name='bookings', to='clientsetup.unit')),
            ],
        ),
        migrations.CreateModel(
            name='BookingApplicant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_primary', models.BooleanField(default=False)),
                ('sequence', models.PositiveSmallIntegerField(default=1, help_text='1 = First Applicant, 2 = Second, etc.')),
                ('title', models.CharField(blank=True, max_length=10)),
                ('full_name', models.CharField(max_length=200)),
                ('relation', models.CharField(blank=True, help_text='For co-applicants: Spouse / Child / Father etc.', max_length=50)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('mobile_number', models.CharField(blank=True, max_length=32)),
                ('pan_no', models.CharField(blank=True, max_length=32)),
                ('aadhar_no', models.CharField(blank=True, max_length=32)),
                ('pan_front', models.FileField(blank=True, null=True, upload_to='booking_docs/pan/front/')),
                ('pan_back', models.FileField(blank=True, null=True, upload_to='booking_docs/pan/back/')),
                ('aadhar_front', models.FileField(blank=True, null=True, upload_to='booking_docs/aadhar/front/')),
                ('aadhar_back', models.FileField(blank=True, null=True, upload_to='booking_docs/aadhar/back/')),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applicants', to='booking.booking')),
            ],
            options={
                'ordering': ['booking', 'sequence'],
            },
        ),
        migrations.CreateModel(
            name='BookingAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('label', models.CharField(blank=True, help_text="Friendly name: e.g. 'Agreement PDF', 'Cheque scan'", max_length=150)),
                ('file', models.FileField(upload_to='booking_attachments/')),
                ('doc_type', models.CharField(blank=True, help_text='Optional code for filtering (AGREEMENT / CHEQUE / OTHER etc.)', max_length=50)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='booking.booking')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BookingKycRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('snapshot', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=16)),
                ('decision_remarks', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('one_time_token', models.CharField(blank=True, max_length=64, null=True, unique=True)),
                ('token_used_at', models.DateTimeField(blank=True, null=True)),
                ('booking', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='kyc_request', to='booking.booking')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='kyc_requests_created', to=settings.AUTH_USER_MODEL)),
                ('decided_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='kyc_requests_decided', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kyc_requests', to='clientsetup.project')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='kyc_requests', to='clientsetup.unit')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['project', 'status'], name='booking_boo_project_af3e87_idx'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['unit'], name='booking_boo_unit_id_e7e6f3_idx'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['sales_lead'], name='booking_boo_sales_l_5c95bf_idx'),
        ),
        migrations.AddIndex(
            model_name='bookingkycrequest',
            index=models.Index(fields=['project', 'status'], name='booking_boo_project_1c6216_idx'),
        ),
        migrations.AddIndex(
            model_name='bookingkycrequest',
            index=models.Index(fields=['unit', 'status'], name='booking_boo_unit_id_469cdc_idx'),
        ),
    ]
