# Generated by Django 5.2.3 on 2025-11-25 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='form_ref_no',
            field=models.CharField(help_text='External form reference / booking form number', max_length=50, null=True, unique=True),
        ),
    ]
