# Generated by Django 5.2.3 on 2025-11-26 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_alter_booking_form_ref_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookingattachment',
            name='bank_name',
            field=models.CharField(blank=True, help_text='Bank name for cheque / RTGS payments', max_length=150),
        ),
        migrations.AddField(
            model_name='bookingattachment',
            name='payment_amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Amount of this particular payment (optional but recommended).', max_digits=14, null=True),
        ),
        migrations.AddField(
            model_name='bookingattachment',
            name='payment_date',
            field=models.DateField(blank=True, help_text='Date of cheque / transaction.', null=True),
        ),
        migrations.AddField(
            model_name='bookingattachment',
            name='payment_mode',
            field=models.CharField(blank=True, choices=[('CHEQUE', 'Cheque'), ('RTGS', 'RTGS / NEFT'), ('UPI', 'UPI'), ('CASH', 'Cash'), ('OTHER', 'Other')], help_text='Fill only for PAYMENT_PROOF – Cheque / RTGS / UPI / Cash / Other', max_length=10),
        ),
        migrations.AddField(
            model_name='bookingattachment',
            name='payment_ref_no',
            field=models.CharField(blank=True, help_text='Cheque no / transaction id / UPI ref, etc.', max_length=100),
        ),
        migrations.AddField(
            model_name='bookingattachment',
            name='remarks',
            field=models.TextField(blank=True, help_text='Any extra notes – e.g. cheque return, re-deposited, etc.'),
        ),
        migrations.AlterField(
            model_name='bookingattachment',
            name='doc_type',
            field=models.CharField(blank=True, choices=[('AGREEMENT_PDF', 'Agreement PDF'), ('BOOKING_FORM_PDF', 'Booking Form PDF'), ('PAYMENT_PROOF', 'Payment Proof'), ('OTHER', 'Other')], help_text='AGREEMENT_PDF / BOOKING_FORM_PDF / PAYMENT_PROOF / OTHER', max_length=50),
        ),
    ]
