# Generated by Django 5.2.3 on 2025-11-27 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_bookingattachment_bank_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookingattachment',
            name='doc_type',
            field=models.CharField(blank=True, choices=[('AGREEMENT_PDF', 'Agreement PDF'), ('BOOKING_FORM_PDF', 'Booking Form PDF'), ('PAYMENT_PROOF', 'Payment Proof'), ('IDENTITY_PROOF', 'Identity Proof'), ('OTHER', 'Other')], help_text='AGREEMENT_PDF / BOOKING_FORM_PDF / PAYMENT_PROOF / OTHER', max_length=50),
        ),
        migrations.AlterField(
            model_name='bookingattachment',
            name='payment_mode',
            field=models.CharField(blank=True, choices=[('CHEQUE', 'Cheque'), ('RTGS', 'RTGS / NEFT'), ('UPI', 'UPI'), ('CASH', 'Cash'), ('OTHER', 'Other')], help_text='Fill only for PAYMENT_PROOF – Cheque / RTGS / UPI / Cash / Other', max_length=10, null=True),
        ),
    ]
