# Generated by Django 5.2.3 on 2025-11-28 19:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0004_alter_bookingattachment_doc_type_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='confirmed_by',
            field=models.ForeignKey(blank=True, help_text='User who confirmed (BOOKED) this booking', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookings_confirmed', to=settings.AUTH_USER_MODEL),
        ),
    ]
