# Generated by Django 5.2.3 on 2025-11-29 17:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0005_booking_confirmed_by'),
        ('clientsetup', '0006_parkinginventory_parkingstatushistory_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BookingParkingAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_primary', models.BooleanField(default=True, help_text='In case of multiple slots, mark main slot')),
                ('remarks', models.CharField(blank=True, max_length=255)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parking_allocations', to='booking.booking')),
                ('parking', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='allocations', to='clientsetup.parkinginventory')),
            ],
            options={
                'unique_together': {('booking', 'parking')},
            },
        ),
        migrations.AddField(
            model_name='booking',
            name='parking_slots',
            field=models.ManyToManyField(blank=True, help_text='Parking slots allocated for this booking', related_name='bookings', through='booking.BookingParkingAllocation', to='clientsetup.parkinginventory'),
        ),
        migrations.CreateModel(
            name='BookingStatusHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('old_status', models.CharField(blank=True, choices=[('DRAFT', 'Draft'), ('BLOCKED', 'Blocked'), ('BOOKED', 'Booked'), ('CANCELLED', 'Cancelled')], max_length=16)),
                ('new_status', models.CharField(choices=[('DRAFT', 'Draft'), ('BLOCKED', 'Blocked'), ('BOOKED', 'Booked'), ('CANCELLED', 'Cancelled')], max_length=16)),
                ('old_kyc_status', models.CharField(blank=True, choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], max_length=12)),
                ('new_kyc_status', models.CharField(blank=True, choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], max_length=12)),
                ('action', models.CharField(choices=[('CREATE', 'Create'), ('CONFIRM', 'Confirm'), ('REJECT', 'Reject'), ('AUTO', 'Auto Update'), ('MANUAL_UPDATE', 'Manual Update')], default='MANUAL_UPDATE', help_text='What caused this change? e.g. CONFIRM / REJECT / CREATE', max_length=20)),
                ('reason', models.CharField(blank=True, help_text='Reason given by user (if any).', max_length=255)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='booking.booking')),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='booking_status_changes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['booking', 'new_status'], name='booking_boo_booking_f0315f_idx')],
            },
        ),
    ]
