# Generated by Django 5.2.3 on 2025-11-30 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0006_bookingparkingallocation_booking_parking_slots_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='form_ref_no',
            field=models.CharField(blank=True, help_text='External form reference / booking form number', max_length=50, null=True, unique=True),
        ),
    ]
