# Generated by Django 5.2.3 on 2025-12-06 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0007_alter_booking_form_ref_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='parking_count',
            field=models.PositiveIntegerField(default=0, help_text='Total number of parking slots allotted in this booking'),
        ),
        migrations.AddField(
            model_name='booking',
            name='parking_total_amount',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Total amount for all allotted parking slots', max_digits=14),
        ),
    ]
