# Generated by Django 5.2.3 on 2025-12-06 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0008_booking_parking_count_booking_parking_total_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='development_charges_amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Development Charges amount.', max_digits=14, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='electrical_water_piped_gas_charges_amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Electrical, Water & Piped Gas Connection Charges amount.', max_digits=14, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='legal_compliance_charges_amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Legal & Compliance Charges amount.', max_digits=14, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='possessional_gst_amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='GST amount on possessional charges.', max_digits=14, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='provisional_maintenance_amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Provisional Maintenance amount.', max_digits=14, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='share_application_money_membership_amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Share Application Money & Membership Fees amount.', max_digits=14, null=True),
        ),
    ]
