# Generated by Django 5.2.3 on 2025-12-07 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0009_booking_development_charges_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='customer_base_price_psf',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Negotiated base rate per sq.ft at the time of booking', max_digits=12, null=True, verbose_name='Customer Base Price (per sq.ft)'),
        ),
    ]
