# Generated by Django 5.2.3 on 2025-12-08 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0010_booking_customer_base_price_psf'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='signed_booking_file',
            field=models.FileField(blank=True, help_text='Scanned signed booking form (PDF/image).', null=True, upload_to='booking_signed_forms/'),
        ),
    ]
