# Generated by Django 5.2.3 on 2025-12-11 07:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0011_booking_signed_booking_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='development_charges_psf',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Development Charges rate per sq.ft (snapshot).', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='discount_amount',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Total discount amount applied on this deal.', max_digits=14),
        ),
        migrations.AddField(
            model_name='booking',
            name='gst_percent',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='GST percentage applied (e.g. 5.00 or 18.00).', max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='provisional_maintenance_months',
            field=models.PositiveIntegerField(blank=True, help_text='Number of months considered for provisional maintenance.', null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='stamp_duty_percent',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Stamp duty percentage used for this booking.', max_digits=5, null=True),
        ),
        migrations.CreateModel(
            name='BookingAdditionalCharge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('label', models.CharField(help_text='Name of the charge (e.g. Club House, Floor Rise).', max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Amount for this additional charge.', max_digits=14)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='additional_charges', to='booking.booking')),
            ],
            options={
                'verbose_name': 'Booking Additional Charge',
                'verbose_name_plural': 'Booking Additional Charges',
            },
        ),
    ]
