# Generated by Django 5.2.3 on 2025-11-17 16:41

import django.db.models.deletion
import django.utils.timezone
import salelead.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('channel', '0001_initial'),
        ('clientsetup', '0001_initial'),
        ('leadmanage', '0001_initial'),
        ('setup', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SalesLead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('first_name', models.CharField(blank=True, max_length=150, null=True)),
                ('last_name', models.CharField(blank=True, max_length=150, null=True)),
                ('unknown_channel_partner', models.CharField(blank=True, help_text='CP / broker / agency name if not registered in system', max_length=255, null=True)),
                ('walking', models.BooleanField(default=False, help_text='True if this lead is a walk-in (direct) lead.')),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('mobile_number', models.CharField(blank=True, max_length=32)),
                ('tel_res', models.CharField(blank=True, max_length=32)),
                ('tel_office', models.CharField(blank=True, max_length=32)),
                ('company', models.CharField(blank=True, max_length=150)),
                ('budget', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('annual_income', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('assign_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_sales_leads_next', to=settings.AUTH_USER_MODEL)),
                ('channel_partner', models.ForeignKey(blank=True, help_text='If this lead came via a registered Channel Partner', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales_leads', to='channel.channelpartnerprofile')),
                ('classification', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales_leads_primary', to='leadmanage.leadclassification')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales_lead_created', to=settings.AUTH_USER_MODEL)),
                ('current_owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_sales_leads', to=settings.AUTH_USER_MODEL)),
                ('first_owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='first_owned_sales_leads', to=settings.AUTH_USER_MODEL)),
                ('offering_types', models.ManyToManyField(blank=True, related_name='sales_leads', to='setup.offeringtype')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales_leads', to='clientsetup.project')),
                ('purpose', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales_leads_purpose', to='leadmanage.leadpurpose')),
                ('source', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales_leads_source', to='leadmanage.leadsource')),
                ('status', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales_leads_status', to='leadmanage.leadstatus')),
                ('sub_classification', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales_leads_secondary', to='leadmanage.leadclassification')),
                ('sub_source', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales_leads_sub_source', to='leadmanage.leadsource')),
                ('sub_status', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales_leads_sub_status', to='leadmanage.leadsubstatus')),
            ],
        ),
        migrations.CreateModel(
            name='SalesLeadAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('flat_or_building', models.CharField(blank=True, max_length=120)),
                ('area', models.CharField(blank=True, max_length=120)),
                ('pincode', models.CharField(blank=True, max_length=20)),
                ('city', models.CharField(blank=True, max_length=80)),
                ('state', models.CharField(blank=True, max_length=80)),
                ('country', models.CharField(blank=True, max_length=80)),
                ('description', models.TextField(blank=True)),
                ('sales_lead', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='address', to='salelead.saleslead')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SalesLeadCPInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('referral_code', models.CharField(blank=True, max_length=64)),
                ('cp_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cp_sales_leads', to=settings.AUTH_USER_MODEL)),
                ('sales_lead', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cp_info', to='salelead.saleslead')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SalesLeadDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(blank=True, max_length=150, null=True)),
                ('file', models.FileField(upload_to=salelead.models.sales_lead_document_upload_to)),
                ('sales_lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='salelead.saleslead')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SalesLeadPersonalInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('date_of_anniversary', models.DateField(blank=True, null=True)),
                ('already_part_of_family', models.BooleanField(default=False)),
                ('secondary_email', models.EmailField(blank=True, max_length=254)),
                ('alternate_mobile', models.CharField(blank=True, max_length=32)),
                ('alternate_tel_res', models.CharField(blank=True, max_length=32)),
                ('alternate_tel_off', models.CharField(blank=True, max_length=32)),
                ('current_residence_type', models.CharField(blank=True, max_length=120)),
                ('facebook', models.URLField(blank=True)),
                ('twitter', models.URLField(blank=True)),
                ('linkedin', models.URLField(blank=True)),
                ('current_residence_ownership', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales_leads', to='setup.residencyownership')),
                ('family_size', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales_leads', to='setup.familysize')),
                ('possession_desired_in', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales_leads', to='setup.possiendesigned')),
                ('sales_lead', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='personal_info', to='salelead.saleslead')),
                ('visiting_on_behalf', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales_leads', to='setup.visitinghalf')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SalesLeadProfessionalInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization_name', models.CharField(blank=True, help_text='Name of the organization', max_length=255)),
                ('office_location', models.CharField(blank=True, max_length=255)),
                ('office_pincode', models.CharField(blank=True, max_length=20)),
                ('designation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales_leads', to='setup.designation')),
                ('occupation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales_leads', to='setup.occupation')),
                ('sales_lead', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='professional_info', to='salelead.saleslead')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SalesLeadProposalDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('file', models.FileField(upload_to=salelead.models.sales_lead_proposal_upload_to)),
                ('sales_lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proposal_documents', to='salelead.saleslead')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SalesLeadStageHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('notes', models.CharField(blank=True, max_length=255)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales_lead_stage_histories_created', to=settings.AUTH_USER_MODEL)),
                ('sales_lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stage_history', to='salelead.saleslead')),
                ('stage', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stage_entries', to='leadmanage.leadstage')),
                ('status', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='status_entries', to='leadmanage.leadstatus')),
                ('sub_status', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sub_status_entries', to='leadmanage.leadsubstatus')),
            ],
            options={
                'ordering': ['-event_date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='SalesLeadUpdate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=150)),
                ('info', models.TextField(blank=True)),
                ('event_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales_lead_updates_created', to=settings.AUTH_USER_MODEL)),
                ('sales_lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='updates', to='salelead.saleslead')),
            ],
            options={
                'ordering': ['-event_date', '-id'],
            },
        ),
        migrations.AddIndex(
            model_name='saleslead',
            index=models.Index(fields=['project'], name='salelead_sa_project_1ad87e_idx'),
        ),
        migrations.AddIndex(
            model_name='saleslead',
            index=models.Index(fields=['current_owner'], name='salelead_sa_current_452366_idx'),
        ),
        migrations.AddIndex(
            model_name='saleslead',
            index=models.Index(fields=['status'], name='salelead_sa_status__1e7991_idx'),
        ),
        migrations.AddIndex(
            model_name='saleslead',
            index=models.Index(fields=['channel_partner'], name='salelead_sa_channel_e8ac6c_idx'),
        ),
        migrations.AddIndex(
            model_name='saleslead',
            index=models.Index(fields=['walking'], name='salelead_sa_walking_d64892_idx'),
        ),
        migrations.AddIndex(
            model_name='salesleadstagehistory',
            index=models.Index(fields=['sales_lead', 'event_date'], name='salelead_sa_sales_l_6afbb1_idx'),
        ),
        migrations.AddIndex(
            model_name='salesleadstagehistory',
            index=models.Index(fields=['stage'], name='salelead_sa_stage_i_c303ee_idx'),
        ),
    ]
