# Generated by Django 5.2.3 on 2025-11-20 11:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientsetup', '0002_project_price_per_sqft'),
        ('salelead', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InterestedLeadUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_primary', models.BooleanField(default=False)),
                ('sales_lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interested_unit_links', to='salelead.saleslead')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lead_interest_links', to='clientsetup.unit')),
            ],
            options={
                'unique_together': {('sales_lead', 'unit')},
            },
        ),
    ]
