# Generated by Django 5.2.3 on 2025-11-20 11:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salelead', '0002_interestedleadunit'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SalesLeadEmailLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_type', models.CharField(choices=[('WELCOME', 'Welcome / Acknowledgement'), ('FOLLOWUP', 'Follow-up'), ('REMINDER', 'Reminder'), ('QUOTATION', 'Quotation / Cost Sheet'), ('OTHER', 'Other')], default='OTHER', help_text='Email ka purpose / category.', max_length=20)),
                ('subject', models.CharField(max_length=255)),
                ('body', models.TextField(help_text='Email body ka snapshot jab bheji gayi.')),
                ('to_email', models.EmailField(help_text='Lead ko bheji gayi email address.', max_length=254)),
                ('cc', models.TextField(blank=True, help_text='Comma-separated CC emails (optional).')),
                ('bcc', models.TextField(blank=True, help_text='Comma-separated BCC emails (optional).')),
                ('from_email', models.EmailField(blank=True, help_text="Jo 'from' address use hua (SMTP / SendGrid, etc.).", max_length=254)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('QUEUED', 'Queued'), ('SENT', 'Sent'), ('FAILED', 'Failed')], default='DRAFT', max_length=10)),
                ('sent_at', models.DateTimeField(blank=True, help_text='Jab actual mail provider ko bheja gaya.', null=True)),
                ('provider_message_id', models.CharField(blank=True, help_text='Mail provider ka message ID (SendGrid, SMTP ID, etc.).', max_length=255)),
                ('error_message', models.TextField(blank=True, help_text='Agar FAILED hua to error ka message.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sales_lead', models.ForeignKey(help_text='Jis lead ko email gayi.', on_delete=django.db.models.deletion.CASCADE, related_name='email_logs', to='salelead.saleslead')),
                ('sent_by', models.ForeignKey(blank=True, help_text='Jo user ne trigger kiya (ya null agar system ne bheja).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_lead_emails', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Sales Lead Email Log',
                'verbose_name_plural': 'Sales Lead Email Logs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['sales_lead', 'created_at'], name='salelead_sa_sales_l_91c586_idx'), models.Index(fields=['status'], name='salelead_sa_status_0bc917_idx')],
            },
        ),
    ]
