# Generated by Django 5.2.3 on 2025-11-20 11:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('salelead', '0003_salesleademaillog'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salesleademaillog',
            name='error_message',
        ),
        migrations.RemoveField(
            model_name='salesleademaillog',
            name='provider_message_id',
        ),
    ]
