# Generated by Django 5.2.3 on 2025-11-20 19:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salelead', '0004_remove_salesleademaillog_error_message_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LeadComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('stage_at_time', models.CharField(blank=True, help_text='Stage name when this comment was added (optional).', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lead_comments', to=settings.AUTH_USER_MODEL)),
                ('sales_lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='salelead.saleslead')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
