# Generated by Django 5.2.3 on 2025-11-20 19:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leadmanage', '0001_initial'),
        ('salelead', '0005_leadcomment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leadcomment',
            name='stage_at_time',
            field=models.ForeignKey(blank=True, help_text='Stage of this lead when the comment was added', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lead_comments', to='leadmanage.leadstage'),
        ),
    ]
