# Generated by Django 5.2.3 on 2025-11-22 07:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientsetup', '0003_commercialoffer'),
        ('salelead', '0007_saleslead_last_site_visit_at_and_more'),
        ('setup', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='salesleadupdate',
            name='update_type',
            field=models.CharField(choices=[('FOLLOW_UP', 'Follow Up'), ('REMINDER', 'Reminder'), ('NOTE', 'Note'), ('WHATSAPP', 'WhatsApp Message'), ('EMAIL', 'Email'), ('STATUS_CHANGE', 'Status Change'), ('CALL', 'Call Log'), ('OTHER', 'Other')], default='NOTE', max_length=50),
        ),
        migrations.AddField(
            model_name='sitevisit',
            name='inventory_unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='clientsetup.inventory'),
        ),
        migrations.AddField(
            model_name='sitevisit',
            name='unit_config',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='setup.unitconfiguration'),
        ),
        migrations.AlterField(
            model_name='saleslead',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='site_visits_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='sitevisit',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='sitevisit',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='site_visits_updated', to=settings.AUTH_USER_MODEL),
        ),
    ]
