# Generated by Django 5.2.3 on 2025-11-22 07:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientsetup', '0003_commercialoffer'),
        ('salelead', '0008_salesleadupdate_update_type_sitevisit_inventory_unit_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sitevisit',
            name='inventory_unit',
        ),
        migrations.AddField(
            model_name='sitevisit',
            name='inventory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='clientsetup.inventory'),
        ),
    ]
