# Generated by Django 5.2.3 on 2025-11-22 07:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientsetup', '0003_commercialoffer'),
        ('salelead', '0009_remove_sitevisit_inventory_unit_sitevisit_inventory'),
        ('setup', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='saleslead',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Lead_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='sitevisit',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='site_visits_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='sitevisit',
            name='inventory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='site_visits', to='clientsetup.inventory'),
        ),
        migrations.AlterField(
            model_name='sitevisit',
            name='unit_config',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='site_visits', to='setup.unitconfiguration'),
        ),
    ]
