# Generated by Django 5.2.3 on 2025-11-22 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salelead', '0010_alter_saleslead_created_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitevisit',
            name='member_mobile_number',
            field=models.CharField(blank=True, help_text='Mobile number of the member/visitor for this site visit.', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='sitevisit',
            name='member_name',
            field=models.CharField(blank=True, help_text='Name of the member/visitor for this site visit.', max_length=150, null=True),
        ),
    ]
