# Generated by Django 5.2.3 on 2025-11-23 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salelead', '0011_sitevisit_member_mobile_number_sitevisit_member_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitevisit',
            name='member_mobile_number',
            field=models.CharField(blank=True, help_text='Mobile number of the visiting member.', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='sitevisit',
            name='member_name',
            field=models.CharField(blank=True, help_text='Name of the additional member visiting.', max_length=120, null=True),
        ),
    ]
