# Generated by Django 5.2.3 on 2025-11-24 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salelead', '0013_sitevisitreschedulehistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesleadupdate',
            name='reminder_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sitevisit',
            name='reminder_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
