# Generated by Django 5.2.3 on 2025-11-25 05:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientsetup', '0004_inventory_blocked_until_notification_content_type_and_more'),
        ('salelead', '0015_salesleadstatushistory'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LeadOpportunity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source_system', models.CharField(choices=[('META', 'Meta / Facebook Ads'), ('GOOGLE_SHEET', 'Google Sheet'), ('GOOGLE_ADS', 'Google Ads'), ('WEB_FORM', 'Website Form'), ('PORTAL', 'Property Portal'), ('OTHER', 'Other / Manual Import')], default='META', help_text='From where this opportunity came (Meta, Sheet, Web, etc.).', max_length=50)),
                ('source_name', models.CharField(blank=True, help_text='Optional: sheet name, form name, integration name, etc.', max_length=255)),
                ('source_lead_id', models.CharField(blank=True, help_text='ID from Meta / form / sheet row id, used for de-duplication.', max_length=255)),
                ('import_batch_id', models.CharField(blank=True, help_text='Batch id for imports (e.g. one Google Sheet upload).', max_length=100)),
                ('status', models.CharField(choices=[('NEW', 'New (not reviewed)'), ('IN_REVIEW', 'In Review'), ('CONVERTED', 'Converted to Lead'), ('JUNK', 'Marked as Junk'), ('DUPLICATE', 'Duplicate / Merged')], default='NEW', max_length=20)),
                ('full_name', models.CharField(blank=True, max_length=255)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('mobile_number', models.CharField(blank=True, max_length=32)),
                ('raw_payload', models.JSONField(blank=True, help_text='Full raw JSON/body from the source for debugging and re-parsing.', null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lead_opportunities_created', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(blank=True, help_text='Project detected from sheet/meta mapping (optional).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lead_opportunities', to='clientsetup.project')),
                ('source_opportunity', models.ForeignKey(blank=True, help_text='If this lead came from a raw imported opportunity (Meta/Sheet/Web/etc.).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='converted_leads', to='salelead.leadopportunity')),
            ],
            options={
                'verbose_name': 'Lead Opportunity',
                'verbose_name_plural': 'Lead Opportunities',
                'indexes': [models.Index(fields=['source_system'], name='salelead_le_source__c33ec4_idx'), models.Index(fields=['source_lead_id'], name='salelead_le_source__dc106d_idx'), models.Index(fields=['status'], name='salelead_le_status_50ffa3_idx'), models.Index(fields=['project'], name='salelead_le_project_59489a_idx')],
                'unique_together': {('source_system', 'source_lead_id')},
            },
        ),
    ]
