# Generated by Django 5.2.3 on 2025-11-25 12:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientsetup', '0004_inventory_blocked_until_notification_content_type_and_more'),
        ('salelead', '0016_leadopportunity'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='leadopportunity',
            name='salelead_le_source__dc106d_idx',
        ),

        migrations.AddField(
            model_name='leadopportunity',
            name='external_id',
            field=models.CharField(
                max_length=255,
                blank=True,
                help_text='ID from Meta / form / sheet row / portal, used for de-duplication.',
            ),
        ),

        # 3) Ab unique_together mein external_id use karo
        migrations.AlterUniqueTogether(
            name='leadopportunity',
            unique_together={('source_system', 'external_id')},
        ),

        # 4) Baaki normal field changes
        migrations.AlterField(
            model_name='leadopportunity',
            name='project',
            field=models.ForeignKey(
                blank=True,
                help_text='Project detected from sheet/meta/portal mapping (optional).',
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='lead_opportunities',
                to='clientsetup.project',
            ),
        ),
        migrations.AlterField(
            model_name='leadopportunity',
            name='source_name',
            field=models.CharField(
                max_length=255,
                blank=True,
                help_text='Optional: sheet name, form name, portal name, campaign name etc.',
            ),
        ),
        migrations.AlterField(
            model_name='leadopportunity',
            name='source_system',
            field=models.CharField(
                max_length=50,
                choices=[
                    ('META', 'Meta / Facebook Ads'),
                    ('GOOGLE_SHEET', 'Google Sheet'),
                    ('GOOGLE_ADS', 'Google Ads'),
                    ('WEB_FORM', 'Website Form'),
                    ('PORTAL', 'Property Portal'),
                    ('WHATSAPP', 'WhatsApp'),
                    ('CHATBOT', 'Chatbot'),
                    ('OTHER', 'Other / Manual Import'),
                ],
                default='OTHER',
                help_text='From where this opportunity came (Meta, Sheet, Web, Portal, etc.).',
            ),
        ),

        # 5) external_id par index
        migrations.AddIndex(
            model_name='leadopportunity',
            index=models.Index(
                fields=['external_id'],
                name='salelead_le_externa_5debe5_idx',
            ),
        ),

        migrations.AddField(
            model_name='saleslead',
            name='source_opportunity',
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='sales_lead',
                to='salelead.leadopportunity',
                help_text='If this SalesLead was created from an imported LeadOpportunity.',
            ),
        ),

        # 7) LeadOpportunity se purane fields hatao
        migrations.RemoveField(
            model_name='leadopportunity',
            name='source_lead_id',
        ),
        migrations.RemoveField(
            model_name='leadopportunity',
            name='source_opportunity',
        ),
    ]
