# Generated by Django 5.2.3 on 2025-11-25 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salelead', '0017_remove_leadopportunity_salelead_le_source__dc106d_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeadEmailOTP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('otp_code', models.CharField(max_length=6)),
                ('is_verified', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('attempts', models.PositiveIntegerField(default=0)),
            ],
            options={
                'indexes': [models.Index(fields=['email', 'is_verified'], name='salelead_le_email_ba15b0_idx')],
            },
        ),
    ]
