# Generated by Django 5.2.3 on 2025-11-26 13:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientsetup', '0004_inventory_blocked_until_notification_content_type_and_more'),
        ('salelead', '0018_leademailotp'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalesLeadUpdateStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True)),
                ('label', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clientsetup.project')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.AddField(
            model_name='salesleadupdate',
            name='activity_status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='updates', to='salelead.salesleadupdatestatus'),
        ),
    ]
