# Generated by Django 5.2.3 on 2025-11-26 16:08

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salelead', '0019_salesleadupdatestatus_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SalesLeadUpdateStatusHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('comment', models.TextField(blank=True)),
                ('event_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales_lead_update_status_changes', to=settings.AUTH_USER_MODEL)),
                ('new_status', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='salelead.salesleadupdatestatus')),
                ('old_status', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='salelead.salesleadupdatestatus')),
                ('sales_lead_update', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='salelead.salesleadupdate')),
            ],
            options={
                'ordering': ['-event_date', '-id'],
            },
        ),
    ]
