# Generated by Django 5.2.3 on 2025-11-26 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salelead', '0020_salesleadupdatestatushistory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesleadupdatestatus',
            name='code',
            field=models.CharField(max_length=50),
        ),
    ]
