# Generated by Django 5.2.3 on 2025-11-27 12:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientsetup', '0004_inventory_blocked_until_notification_content_type_and_more'),
        ('salelead', '0021_alter_salesleadupdatestatus_code'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LeadOpportunityStatusConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(choices=[('NEW', 'New (not reviewed)'), ('IN_REVIEW', 'In Review'), ('CONVERTED', 'Converted to Lead'), ('JUNK', 'Marked as Junk'), ('DUPLICATE', 'Duplicate / Merged')], help_text='Status code stored on LeadOpportunity.status.', max_length=20)),
                ('label', models.CharField(help_text='Human readable label to show in the UI.', max_length=100)),
                ('can_convert', models.BooleanField(default=False, help_text="If true, when an opportunity is moved to this status we will automatically create a SalesLead from it (if it's not already converted).")),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='opportunity_status_configs_created', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(blank=True, help_text='If null, this status config is global and can be used for all projects.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='opportunity_status_configs', to='clientsetup.project')),
            ],
            options={
                'verbose_name': 'Lead Opportunity Status Config',
                'verbose_name_plural': 'Lead Opportunity Status Configs',
                'unique_together': {('project', 'code')},
            },
        ),
        migrations.AddField(
            model_name='leadopportunity',
            name='status_config',
            field=models.ForeignKey(blank=True, help_text='Resolved status configuration (project specific / global) for this opportunity.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='opportunities', to='salelead.leadopportunitystatusconfig'),
        ),
    ]
