# Generated by Django 5.2.3 on 2025-11-27 12:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salelead', '0022_leadopportunitystatusconfig_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LeadOpportunityStatusHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('comment', models.TextField(blank=True)),
                ('auto_converted', models.BooleanField(default=False)),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lead_opportunity_status_changes', to=settings.AUTH_USER_MODEL)),
                ('new_status_config', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='new_status_histories', to='salelead.leadopportunitystatusconfig')),
                ('old_status_config', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='old_status_histories', to='salelead.leadopportunitystatusconfig')),
                ('opportunity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='salelead.leadopportunity')),
                ('sales_lead', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='opportunity_status_changes', to='salelead.saleslead')),
            ],
            options={
                'verbose_name': 'Lead Opportunity Status History',
                'verbose_name_plural': 'Lead Opportunity Status Histories',
                'ordering': ['-created_at'],
            },
        ),
    ]
