# Generated by Django 5.2.3 on 2025-11-27 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salelead', '0023_leadopportunitystatushistory'),
        ('setup', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='saleslead',
            name='company',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='saleslead',
            name='offering_types',
            field=models.ManyToManyField(blank=True, null=True, related_name='sales_leads', to='setup.offeringtype'),
        ),
        migrations.AlterField(
            model_name='saleslead',
            name='tel_office',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='saleslead',
            name='tel_res',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
