# Generated by Django 5.2.3 on 2025-11-28 06:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salelead', '0025_leadopportunityattachment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='leadopportunity',
            name='owner',
            field=models.ForeignKey(blank=True, help_text='User responsible for this opportunity.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lead_opportunities_owned', to=settings.AUTH_USER_MODEL),
        ),
    ]
