# Generated by Django 5.2.3 on 2025-11-28 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salelead', '0026_leadopportunity_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leadopportunity',
            name='source_system',
            field=models.CharField(choices=[('META', 'Meta / Facebook Ads'), ('GOOGLE_SHEET', 'Google Sheet'), ('GOOGLE_ADS', 'Google Ads'), ('WEB_FORM', 'Website Form'), ('PORTAL', 'Property Portal'), ('WHATSAPP', 'WhatsApp'), ('CHATBOT', 'Chatbot'), ('CALLING', 'Calling Data Upload'), ('OTHER', 'Other / Manual Import')], default='OTHER', help_text='From where this opportunity came (Meta, Sheet, Web, Portal, etc.).', max_length=50),
        ),
    ]
