# Generated by Django 5.2.3 on 2025-11-29 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salelead', '0027_alter_leadopportunity_source_system'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitevisit',
            name='status',
            field=models.CharField(choices=[('SCHEDULED', 'Scheduled'), ('RESCHEDULED', 'Rescheduled'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled'), ('NO_SHOW', 'No Show')], default='SCHEDULED', max_length=20),
        ),
    ]
