# Generated by Django 5.2.3 on 2025-11-29 08:17

import django.db.models.deletion
import django.utils.timezone
import salelead.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0005_booking_confirmed_by'),
        ('clientsetup', '0005_project_at_lead_time_email'),
        ('salelead', '0028_alter_sitevisit_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentLead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_type', models.CharField(choices=[('EOI', 'EOI'), ('BOOKING', 'Booking')], max_length=20)),
                ('payment_method', models.CharField(choices=[('ONLINE', 'Online'), ('POS', 'POS'), ('DRAFT_CHEQUE', 'Draft / Cheque'), ('NEFT_RTGS', 'NEFT / RTGS')], max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('payment_date', models.DateTimeField(default=django.utils.timezone.now, help_text='When payment was received / initiated.')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('SUCCESS', 'Success'), ('FAILED', 'Failed'), ('REFUNDED', 'Refunded')], default='PENDING', max_length=20)),
                ('notes', models.TextField(blank=True, null=True)),
                ('payment_mode', models.CharField(blank=True, help_text='For ONLINE/POS: UPI, Card, NetBanking, Wallet, etc.', max_length=50, null=True)),
                ('transaction_no', models.CharField(blank=True, help_text='PG transaction id / POS transaction no.', max_length=100, null=True)),
                ('pos_slip_image', models.ImageField(blank=True, help_text='Image of POS charge slip.', null=True, upload_to=salelead.models.payment_pos_upload_to)),
                ('cheque_number', models.CharField(blank=True, max_length=50, null=True)),
                ('cheque_date', models.DateField(blank=True, null=True)),
                ('bank_name', models.CharField(blank=True, max_length=150, null=True)),
                ('ifsc_code', models.CharField(blank=True, max_length=20, null=True)),
                ('branch_name', models.CharField(blank=True, max_length=150, null=True)),
                ('cheque_image', models.ImageField(blank=True, help_text='Scanned cheque image.', null=True, upload_to=salelead.models.payment_cheque_upload_to)),
                ('neft_rtgs_ref_no', models.CharField(blank=True, help_text='NEFT / RTGS reference number.', max_length=100, null=True)),
                ('booking', models.ForeignKey(blank=True, help_text='Optional link to final booking, if created.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lead_payments', to='booking.booking')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lead_payments_created', to=settings.AUTH_USER_MODEL)),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='salelead.saleslead')),
                ('project', models.ForeignKey(help_text='Denormalised from SalesLead.project for faster filters.', on_delete=django.db.models.deletion.CASCADE, related_name='lead_payments', to='clientsetup.project')),
            ],
            options={
                'ordering': ['-payment_date', '-id'],
                'indexes': [models.Index(fields=['project'], name='salelead_pa_project_8a5ab2_idx'), models.Index(fields=['lead'], name='salelead_pa_lead_id_573c74_idx'), models.Index(fields=['payment_type'], name='salelead_pa_payment_ece532_idx'), models.Index(fields=['payment_method'], name='salelead_pa_payment_d8030a_idx'), models.Index(fields=['status'], name='salelead_pa_status_baff5a_idx')],
            },
        ),
    ]
