# Generated by Django 5.2.3 on 2025-11-29 09:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leadmanage', '0003_leadstage_for_site'),
        ('salelead', '0029_paymentlead'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesleadpersonalinfo',
            name='current_residence_ownership',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales_leads', to='leadmanage.residencyownership'),
        ),
        migrations.AlterField(
            model_name='salesleadpersonalinfo',
            name='family_size',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales_leads', to='leadmanage.familysize'),
        ),
        migrations.AlterField(
            model_name='salesleadpersonalinfo',
            name='possession_desired_in',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales_leads', to='leadmanage.possiendesigned'),
        ),
        migrations.AlterField(
            model_name='salesleadpersonalinfo',
            name='visiting_on_behalf',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales_leads', to='leadmanage.visitinghalf'),
        ),
    ]
