# Generated by Django 5.2.3 on 2025-11-29 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salelead', '0030_alter_salesleadpersonalinfo_current_residence_ownership_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesleadupdate',
            name='update_type',
            field=models.CharField(choices=[('FOLLOW_UP', 'Follow Up'), ('REMINDER', 'Reminder'), ('NOTE', 'Note'), ('SITE_VISIT', 'Site Visit'), ('WHATSAPP', 'WhatsApp Message'), ('EMAIL', 'Email'), ('STATUS_CHANGE', 'Status Change'), ('CALL', 'Call Log'), ('OTHER', 'Other')], default='NOTE', max_length=50),
        ),
    ]
