# Generated by Django 5.2.3 on 2025-11-30 09:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salelead', '0031_alter_salesleadupdate_update_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SalesLeadChangeLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('action', models.CharField(choices=[('CREATE', 'Create'), ('UPDATE', 'Update'), ('STATUS_CHANGE', 'Status Change'), ('OWNER_CHANGE', 'Owner Change'), ('NOTE', 'Note / Comment'), ('OTHER', 'Other')], default='UPDATE', max_length=32)),
                ('snapshot_before', models.JSONField(blank=True, null=True)),
                ('snapshot_after', models.JSONField(blank=True, null=True)),
                ('changes', models.JSONField(blank=True, null=True)),
                ('comment', models.TextField(blank=True)),
                ('request_meta', models.JSONField(blank=True, null=True)),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='saleslead_change_logs', to=settings.AUTH_USER_MODEL)),
                ('sales_lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='change_logs', to='salelead.saleslead')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
