# Generated by Django 5.2.3 on 2025-12-01 09:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salelead', '0032_salesleadchangelog'),
        ('setup', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='saleslead',
            name='age_group',
            field=models.CharField(blank=True, choices=[('LT20', '<20'), ('20_25', '20-25'), ('26_35', '26-35'), ('36_45', '36-45'), ('46_60', '46-60'), ('GT60', '>60')], help_text='Age bracket like 20-25, 26-35, etc.', max_length=16, null=True),
        ),
        migrations.AddField(
            model_name='saleslead',
            name='nationality',
            field=models.CharField(blank=True, choices=[('INDIAN', 'Indian'), ('NRI', 'NRI'), ('OTHER', 'Others')], help_text='Indian / NRI / Others as per customer form.', max_length=16, null=True),
        ),
        migrations.AddField(
            model_name='saleslead',
            name='unit_configuration',
            field=models.ForeignKey(blank=True, help_text='2 BHK / 3 BHK / 4 BHK (Jodi) etc.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales_leads', to='setup.unitconfiguration'),
        ),
        migrations.AlterField(
            model_name='saleslead',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
