# Generated by Django 5.2.3 on 2025-12-02 07:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('channel', '0007_alter_channelpartnerprofile_source'),
        ('clientsetup', '0009_project_price_per_parking'),
        ('leadmanage', '0003_leadstage_for_site'),
        ('salelead', '0033_saleslead_age_group_saleslead_nationality_and_more'),
        ('setup', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sitevisit',
            options={'ordering': ['-scheduled_at', '-id']},
        ),
        migrations.RemoveField(
            model_name='sitevisit',
            name='completed_at',
        ),
        migrations.AddField(
            model_name='sitevisit',
            name='actual_end_at',
            field=models.DateTimeField(blank=True, help_text='Actual check-out time.', null=True),
        ),
        migrations.AddField(
            model_name='sitevisit',
            name='actual_start_at',
            field=models.DateTimeField(blank=True, help_text='Actual check-in time at site.', null=True),
        ),
        migrations.AddField(
            model_name='sitevisit',
            name='channel_partner',
            field=models.ForeignKey(blank=True, help_text='Channel partner responsible (if any).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='site_visits', to='channel.channelpartnerprofile'),
        ),
        migrations.AddField(
            model_name='sitevisit',
            name='google_maps_link',
            field=models.URLField(blank=True, help_text='Google Maps link for the meeting point (optional).', max_length=500),
        ),
        migrations.AddField(
            model_name='sitevisit',
            name='internal_notes',
            field=models.TextField(blank=True, help_text='Internal notes (not to be shared with customer).'),
        ),
        migrations.AddField(
            model_name='sitevisit',
            name='lead_stage',
            field=models.ForeignKey(blank=True, help_text='Lead stage at the time of this visit (optional).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='site_visits', to='leadmanage.leadstage'),
        ),
        migrations.AddField(
            model_name='sitevisit',
            name='location_name',
            field=models.CharField(blank=True, help_text="Eg. 'Site Office', 'Sample Flat - Tower A', etc.", max_length=255),
        ),
        migrations.AddField(
            model_name='sitevisit',
            name='meeting_address',
            field=models.TextField(blank=True, help_text='Full address if different from default project address.'),
        ),
        migrations.AddField(
            model_name='sitevisit',
            name='member_count',
            field=models.PositiveIntegerField(default=1, help_text='Total people expected in the visit (lead + family).'),
        ),
        migrations.AddField(
            model_name='sitevisit',
            name='next_reminder_at',
            field=models.DateTimeField(blank=True, help_text='If set, Celery/cron can use this to plan next reminder.', null=True),
        ),
        migrations.AddField(
            model_name='sitevisit',
            name='no_show_reason',
            field=models.TextField(blank=True, help_text='Reason if customer did not show up (status=NO_SHOW).', null=True),
        ),
        migrations.AddField(
            model_name='sitevisit',
            name='outcome',
            field=models.CharField(blank=True, choices=[('HOT', 'Hot – High Interest'), ('WARM', 'Warm – Considering'), ('COLD', 'Cold – Not Interested'), ('HOLD', 'Hold – Need Time'), ('BOOKED', 'Booked / Converted'), ('NO_DECISION', 'No Clear Decision'), ('OTHER', 'Other')], help_text='Post-visit outcome / interest level.', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='sitevisit',
            name='outcome_notes',
            field=models.TextField(blank=True, help_text='Detailed notes / summary of discussion, objections, requirements.', null=True),
        ),
        migrations.AddField(
            model_name='sitevisit',
            name='pickup_details',
            field=models.TextField(blank=True, help_text='Cab details, driver number, pickup point etc.'),
        ),
        migrations.AddField(
            model_name='sitevisit',
            name='pickup_required',
            field=models.BooleanField(default=False, help_text='Whether cab / pickup is required.'),
        ),
        migrations.AddField(
            model_name='sitevisit',
            name='public_notes',
            field=models.TextField(blank=True, help_text='General notes visible to sales team.'),
        ),
        migrations.AddField(
            model_name='sitevisit',
            name='rating',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Optional 1–5 rating for interest / seriousness.', null=True),
        ),
        migrations.AddField(
            model_name='sitevisit',
            name='reminder_count',
            field=models.PositiveIntegerField(default=0, help_text='How many reminders were sent.'),
        ),
        migrations.AddField(
            model_name='sitevisit',
            name='scheduled_end_at',
            field=models.DateTimeField(blank=True, help_text='Planned end time (for better planning & reporting).', null=True),
        ),
        migrations.AddField(
            model_name='sitevisit',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='sitevisit',
            name='visit_number',
            field=models.PositiveIntegerField(default=1, help_text='1 = first visit for this lead, 2 = second visit, etc.'),
        ),
        migrations.AddField(
            model_name='sitevisit',
            name='visit_type',
            field=models.CharField(choices=[('FIRST', 'First Visit'), ('REVISIT', 'Revisit'), ('CLOSING', 'Closing / Negotiation'), ('POSSESSION', 'Possession / Handover'), ('OTHER', 'Other')], default='FIRST', help_text='Type of visit – first, revisit, closing etc.', max_length=20),
        ),
        migrations.AlterField(
            model_name='sitevisit',
            name='cancelled_at',
            field=models.DateTimeField(blank=True, help_text='When the visit was cancelled (if status=CANCELLED).', null=True),
        ),
        migrations.AlterField(
            model_name='sitevisit',
            name='cancelled_reason',
            field=models.TextField(blank=True, help_text='Free text reason for cancellation.', null=True),
        ),
        migrations.AlterField(
            model_name='sitevisit',
            name='lead',
            field=models.ForeignKey(help_text='Primary lead for whom this visit is scheduled.', on_delete=django.db.models.deletion.CASCADE, related_name='site_visits', to='salelead.saleslead'),
        ),
        migrations.AlterField(
            model_name='sitevisit',
            name='member_name',
            field=models.CharField(blank=True, help_text='Name of the main visitor (if different from lead).', max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='sitevisit',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='site_visits', to='clientsetup.project'),
        ),
        migrations.AlterField(
            model_name='sitevisit',
            name='reminder_sent_at',
            field=models.DateTimeField(blank=True, help_text='Last reminder sent datetime.', null=True),
        ),
        migrations.AlterField(
            model_name='sitevisit',
            name='scheduled_at',
            field=models.DateTimeField(help_text='Planned date & time for the visit.'),
        ),
        migrations.AddIndex(
            model_name='sitevisit',
            index=models.Index(fields=['actual_start_at'], name='salelead_si_actual__7a8214_idx'),
        ),
        migrations.AddIndex(
            model_name='sitevisit',
            index=models.Index(fields=['outcome'], name='salelead_si_outcome_9401fb_idx'),
        ),
    ]
