# Generated by Django 5.2.3 on 2025-12-08 08:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0010_booking_customer_base_price_psf'),
        ('clientsetup', '0012_inventory_approved_limit_price_psf_and_more'),
        ('salelead', '0034_alter_sitevisit_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentlead',
            name='for_kyc',
            field=models.BooleanField(default=False, help_text='If true, this payment is only for KYC and should not be shown in normal payment flows.'),
        ),
        migrations.AddField(
            model_name='paymentlead',
            name='kyc_request',
            field=models.ForeignKey(blank=True, help_text='If this payment is specifically for a Booking KYC request.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='booking.bookingkycrequest'),
        ),
        migrations.AddIndex(
            model_name='paymentlead',
            index=models.Index(fields=['for_kyc'], name='salelead_pa_for_kyc_e2b7e6_idx'),
        ),
    ]
