# Generated by Django 5.2.3 on 2025-12-08 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salelead', '0035_paymentlead_for_kyc_paymentlead_kyc_request_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesleadupdate',
            name='reminder_log',
            field=models.JSONField(blank=True, default=dict, help_text='Map of offset_minutes → ISO datetime when reminder was sent.'),
        ),
        migrations.AddField(
            model_name='sitevisit',
            name='reminder_log',
            field=models.JSONField(blank=True, default=dict, help_text='Map of offset_minutes → ISO datetime when reminder was sent.'),
        ),
    ]
