# Generated by Django 5.2.3 on 2025-12-11 04:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leadmanage', '0003_leadstage_for_site'),
        ('salelead', '0036_salesleadupdate_reminder_log_sitevisit_reminder_log'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesleadprofessionalinfo',
            name='occupation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales_leads', to='leadmanage.occupation'),
        ),
    ]
