# Generated by Django 5.2.3 on 2025-12-19 05:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leadmanage', '0004_leadsource_for_walkin'),
        ('salelead', '0037_alter_salesleadprofessionalinfo_occupation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesleadprofessionalinfo',
            name='designation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales_leads', to='leadmanage.designation'),
        ),
    ]
