# Generated by Django 5.2.3 on 2025-12-19 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salelead', '0038_alter_salesleadprofessionalinfo_designation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leadopportunity',
            name='status',
            field=models.CharField(choices=[('NEW', 'New (not reviewed)'), ('IN_REVIEW', 'In Review'), ('CONVERTED', 'Converted to Lead'), ('JUNK', 'Marked as Junk'), ('DUPLICATE', 'Duplicate / Merged'), ('RINGING_BUSY', 'RINGIING/BUSY'), ('DETAILS', 'DETAILS SHARED'), ('SV_LINEUP', 'SV LINE UP'), ('SV_DONE', 'SV DONE'), ('RV_DONE', 'RV DONE'), ('NOT_INTERESTED', 'NOT INTERESTED'), ('LOW_BUDGET', 'LOW BUDGET'), ('READY_TO_MOVE_IN', 'READY TO MOVE IN'), ('NEAR_POSSESSION', 'NEAR POSSESSION'), ('OTHERS', 'OTHERS')], default='NEW', max_length=20),
        ),
        migrations.AlterField(
            model_name='leadopportunitystatusconfig',
            name='code',
            field=models.CharField(choices=[('NEW', 'New (not reviewed)'), ('IN_REVIEW', 'In Review'), ('CONVERTED', 'Converted to Lead'), ('JUNK', 'Marked as Junk'), ('DUPLICATE', 'Duplicate / Merged'), ('RINGING_BUSY', 'RINGIING/BUSY'), ('DETAILS', 'DETAILS SHARED'), ('SV_LINEUP', 'SV LINE UP'), ('SV_DONE', 'SV DONE'), ('RV_DONE', 'RV DONE'), ('NOT_INTERESTED', 'NOT INTERESTED'), ('LOW_BUDGET', 'LOW BUDGET'), ('READY_TO_MOVE_IN', 'READY TO MOVE IN'), ('NEAR_POSSESSION', 'NEAR POSSESSION'), ('OTHERS', 'OTHERS')], help_text='Status code stored on LeadOpportunity.status.', max_length=20),
        ),
    ]
