# Generated by Django 5.2.3 on 2025-12-19 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salelead', '0039_alter_leadopportunity_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leadopportunity',
            name='source_system',
            field=models.CharField(choices=[('META', 'Meta / Facebook Ads'), ('GOOGLE_SHEET', 'Google Sheet'), ('GOOGLE_ADS', 'Google Ads'), ('WEB_FORM', 'Website Form'), ('PORTAL', 'Property Portal'), ('WHATSAPP', 'WhatsApp'), ('CHATBOT', 'Chatbot'), ('CALLING', 'Calling Data Upload'), ('OTHER', 'Other / Manual Import'), ('DIGITAL', 'Digital'), ('DIRECT', 'Direct/Walk-In'), ('CHANNER_PARTNER', 'Channel Partner')], default='OTHER', help_text='From where this opportunity came (Meta, Sheet, Web, Portal, etc.).', max_length=50),
        ),
    ]
