# Generated by Django 5.2.3 on 2025-11-17 16:41

import django.core.validators
import django.db.models.deletion
import leadmanage.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientsetup', '0001_initial'),
        ('setup', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LeadSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='leadmanage.leadsource')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lead_sources', to='clientsetup.project')),
            ],
            options={
                'ordering': ['project__name', 'parent__id', 'name'],
                'unique_together': {('project', 'name', 'parent')},
            },
        ),
        migrations.CreateModel(
            name='LeadStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lead_statuses', to='clientsetup.project')),
            ],
            options={
                'ordering': ['project__name', 'name'],
                'unique_together': {('project', 'name')},
            },
        ),
        migrations.CreateModel(
            name='ProjectLead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project_description', models.TextField(blank=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to=leadmanage.models.project_lead_logo_upload_to)),
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='lead_setup', to='clientsetup.project')),
            ],
            options={
                'verbose_name': 'Project Lead Setup',
                'verbose_name_plural': 'Project Lead Setup',
            },
        ),
        migrations.CreateModel(
            name='PossienDesigned',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('code', models.CharField(db_index=True, help_text='Stable programmatic code, e.g. RESIDENTIAL, MIXED_USE', max_length=50, unique=True, validators=[django.core.validators.RegexValidator('^[A-Z0-9_]+$', 'Use only A–Z, 0–9 and _')])),
                ('is_active', models.BooleanField(default=True)),
                ('project_lead', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='possession_designed_options', to='leadmanage.projectlead')),
            ],
            options={
                'ordering': ['name'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Occupation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('code', models.CharField(db_index=True, help_text='Stable programmatic code, e.g. RESIDENTIAL, MIXED_USE', max_length=50, unique=True, validators=[django.core.validators.RegexValidator('^[A-Z0-9_]+$', 'Use only A–Z, 0–9 and _')])),
                ('is_active', models.BooleanField(default=True)),
                ('project_lead', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='occupation_options', to='leadmanage.projectlead')),
            ],
            options={
                'ordering': ['name'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LeadBudgetOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('currency', models.CharField(choices=[('INR', 'INR'), ('USD', 'USD'), ('EUR', 'EUR')], default='INR', max_length=8)),
                ('budget_min', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('budget_max', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('offering_types', models.ManyToManyField(blank=True, related_name='lead_budget_offers', to='setup.offeringtype')),
                ('project_lead', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='budget_offer', to='leadmanage.projectlead')),
            ],
            options={
                'verbose_name': 'Lead Budget & Offering',
                'verbose_name_plural': 'Lead Budget & Offering',
            },
        ),
        migrations.CreateModel(
            name='FamilySize',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('code', models.CharField(db_index=True, help_text='Stable programmatic code, e.g. RESIDENTIAL, MIXED_USE', max_length=50, unique=True, validators=[django.core.validators.RegexValidator('^[A-Z0-9_]+$', 'Use only A–Z, 0–9 and _')])),
                ('is_active', models.BooleanField(default=True)),
                ('project_lead', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='family_size_options', to='leadmanage.projectlead')),
            ],
            options={
                'ordering': ['name'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Designation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('code', models.CharField(db_index=True, help_text='Stable programmatic code, e.g. RESIDENTIAL, MIXED_USE', max_length=50, unique=True, validators=[django.core.validators.RegexValidator('^[A-Z0-9_]+$', 'Use only A–Z, 0–9 and _')])),
                ('is_active', models.BooleanField(default=True)),
                ('project_lead', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='designation_options', to='leadmanage.projectlead')),
            ],
            options={
                'ordering': ['name'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ProjectLeadReporting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('report_type', models.CharField(choices=[('SUMMARY', 'Summary'), ('DETAILED', 'Detailed')], default='SUMMARY', max_length=16)),
                ('export_format', models.CharField(choices=[('CSV', 'CSV'), ('XLSX', 'Excel (XLSX)'), ('PDF', 'PDF')], default='CSV', max_length=8)),
                ('frequency', models.CharField(choices=[('DAILY', 'Daily'), ('WEEKLY', 'Weekly'), ('MONTHLY', 'Monthly')], default='WEEKLY', max_length=12)),
                ('project_lead', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='reporting', to='leadmanage.projectlead')),
            ],
            options={
                'verbose_name': 'Project Lead Reporting',
                'verbose_name_plural': 'Project Lead Reporting',
            },
        ),
        migrations.CreateModel(
            name='ProjectLeadSiteVisitSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('enable_scheduled_visits', models.BooleanField(default=True)),
                ('default_followup_days', models.PositiveSmallIntegerField(default=3)),
                ('notify_channels', models.JSONField(blank=True, default=list)),
                ('project_lead', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='site_settings', to='leadmanage.projectlead')),
            ],
            options={
                'verbose_name': 'Project Lead Site Settings',
                'verbose_name_plural': 'Project Lead Site Settings',
            },
        ),
        migrations.CreateModel(
            name='ResidencyOwnerShip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('code', models.CharField(db_index=True, help_text='Stable programmatic code, e.g. RESIDENTIAL, MIXED_USE', max_length=50, unique=True, validators=[django.core.validators.RegexValidator('^[A-Z0-9_]+$', 'Use only A–Z, 0–9 and _')])),
                ('is_active', models.BooleanField(default=True)),
                ('project_lead', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='residency_ownership_options', to='leadmanage.projectlead')),
            ],
            options={
                'ordering': ['name'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='VisitingHalf',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('code', models.CharField(db_index=True, help_text='Stable programmatic code, e.g. RESIDENTIAL, MIXED_USE', max_length=50, unique=True, validators=[django.core.validators.RegexValidator('^[A-Z0-9_]+$', 'Use only A–Z, 0–9 and _')])),
                ('is_active', models.BooleanField(default=True)),
                ('project_lead', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='visiting_half_options', to='leadmanage.projectlead')),
            ],
            options={
                'ordering': ['name'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LeadClassification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='leadmanage.leadclassification')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lead_classifications', to='clientsetup.project')),
            ],
            options={
                'ordering': ['project__name', 'parent__id', 'name'],
                'unique_together': {('project', 'name', 'parent')},
            },
        ),
        migrations.CreateModel(
            name='LeadPurpose',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lead_purposes', to='clientsetup.project')),
            ],
            options={
                'ordering': ['project__name', 'name'],
                'unique_together': {('project', 'name')},
            },
        ),
        migrations.CreateModel(
            name='LeadStage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120)),
                ('order', models.PositiveIntegerField(db_index=True, default=1)),
                ('is_closed', models.BooleanField(default=False)),
                ('is_won', models.BooleanField(default=False)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lead_stages', to='clientsetup.project')),
            ],
            options={
                'ordering': ['project__name', 'order'],
                'unique_together': {('project', 'name')},
            },
        ),
        migrations.CreateModel(
            name='LeadSubStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120)),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sub_statuses', to='leadmanage.leadstatus')),
            ],
            options={
                'ordering': ['status__project__name', 'status__name', 'name'],
                'unique_together': {('status', 'name')},
            },
        ),
        migrations.CreateModel(
            name='NewLeadAssignmentRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('availability_strategy', models.CharField(choices=[('ROUND_ROBIN', 'Round Robin'), ('LEAST_LOAD', 'Least Load'), ('RANDOM', 'Random')], default='ROUND_ROBIN', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.CharField(blank=True, max_length=255)),
                ('assignees', models.ManyToManyField(blank=True, related_name='lead_assignment_pools', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assignment_rules', to='clientsetup.project')),
                ('source', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assignment_rules', to='leadmanage.leadsource')),
                ('project_lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignment_rules', to='leadmanage.projectlead')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['project_lead', 'is_active'], name='leadmanage__project_a4566c_idx'), models.Index(fields=['project'], name='leadmanage__project_3ca192_idx'), models.Index(fields=['source'], name='leadmanage__source__18a6eb_idx')],
            },
        ),
    ]
