# Generated by Django 5.2.3 on 2025-11-27 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leadmanage', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='leadsource',
            name='for_cp',
            field=models.BooleanField(default=False, help_text='Use this source for Channel Partners (CP) selection.'),
        ),
    ]
