# Generated by Django 5.2.3 on 2025-11-28 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leadmanage', '0002_leadsource_for_cp'),
    ]

    operations = [
        migrations.AddField(
            model_name='leadstage',
            name='for_site',
            field=models.BooleanField(default=False, help_text='If true, this stage is used for site / walk-in tracking.'),
        ),
    ]
