# Generated by Django 5.2.3 on 2025-12-11 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leadmanage', '0003_leadstage_for_site'),
    ]

    operations = [
        migrations.AddField(
            model_name='leadsource',
            name='for_walkin',
            field=models.BooleanField(default=False, help_text='Use this source for Channel Partners (CP) selection as Waling.'),
        ),
    ]
