# Generated by Django 5.2.3 on 2025-11-17 18:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('channel', '0001_initial'),
        ('leadmanage', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='channelpartnerprofile',
            name='source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='channel_partners', to='leadmanage.leadsource'),
        ),
    ]
