# Generated by Django 5.2.3 on 2025-11-17 19:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('channel', '0002_channelpartnerprofile_source'),
        ('clientsetup', '0001_initial'),
        ('leadmanage', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='channelpartnerprofile',
            name='source',
            field=models.ForeignKey(blank=True, help_text='Lead source associated with this channel partner', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='channel_partners', to='leadmanage.leadsource'),
        ),
        migrations.AlterUniqueTogether(
            name='channelpartnerprojectauthorization',
            unique_together={('channel_partner', 'project')},
        ),
    ]
