# Generated by Django 5.2.3 on 2025-11-19 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('channel', '0003_alter_channelpartnerprofile_source_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='channelpartnerprofile',
            name='onboarding_status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('ACTIVE', 'Active'), ('SUSPENDED', 'Suspended'), ('TERMINATED', 'Terminated')], default='ACTIVE', max_length=20),
        ),
    ]
