# Generated by Django 5.2.3 on 2025-11-21 07:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('channel', '0004_alter_channelpartnerprofile_onboarding_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='partnertier',
            name='admin',
            field=models.ForeignKey(default=1, help_text='Admin / builder who owns this tier config', limit_choices_to={'role': 'ADMIN'}, on_delete=django.db.models.deletion.CASCADE, related_name='cp_tiers', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='partnertier',
            name='commission_amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Flat commission amount per booking (optional)', max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='partnertier',
            name='commission_percent',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Default CP commission % for this tier, e.g. 2.00 = 2%', max_digits=5, null=True),
        ),
    ]
