# Generated by Django 5.2.3 on 2025-11-25 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('channel', '0005_partnertier_admin_partnertier_commission_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='channelpartnerprofile',
            name='referral_code',
            field=models.CharField(blank=True, db_index=True, help_text='Auto-generated referral code for this channel partner.', max_length=50, null=True, unique=True),
        ),
    ]
