# Generated by Django 5.2.3 on 2025-11-27 19:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('channel', '0006_channelpartnerprofile_referral_code'),
        ('leadmanage', '0002_leadsource_for_cp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='channelpartnerprofile',
            name='source',
            field=models.ForeignKey(blank=True, help_text='Lead source associated with this channel partner (CP only).', limit_choices_to={'for_cp': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='channel_partners', to='leadmanage.leadsource'),
        ),
    ]
