# Generated by Django 5.2.3 on 2025-11-19 07:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientsetup', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CostSheetTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company_name', models.CharField(max_length=255)),
                ('company_logo', models.ImageField(blank=True, null=True, upload_to='costsheet/logos/')),
                ('quotation_header', models.CharField(help_text='Heading shown on Cost Sheet.', max_length=255)),
                ('quotation_subheader', models.CharField(blank=True, max_length=255)),
                ('validity_days', models.PositiveIntegerField(default=7)),
                ('gst_percent', models.DecimalField(decimal_places=2, default=0, help_text='GST percentage (e.g. 5.00, 18.00)', max_digits=5)),
                ('stamp_duty_percent', models.DecimalField(decimal_places=2, default=0, help_text='Stamp duty percentage.', max_digits=5)),
                ('registration_amount', models.DecimalField(decimal_places=2, default=0, help_text='Registration fee amount (absolute value).', max_digits=12)),
                ('legal_fee_amount', models.DecimalField(decimal_places=2, default=0, help_text='Legal fees amount.', max_digits=12)),
                ('terms_and_conditions', models.TextField(blank=True, help_text='Default T&C for this cost sheet template.')),
                ('config', models.JSONField(blank=True, help_text='Any extra JSON config: sections, extra charges schema, etc.', null=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cost_sheet_templates_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ProjectCostSheetTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('extra_charges', models.JSONField(blank=True, help_text='Project specific extra charges config if any.', null=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='project_cost_sheet_templates_created', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_cost_sheet_templates', to='clientsetup.project')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_mappings', to='costsheet.costsheettemplate')),
            ],
            options={
                'unique_together': {('project', 'template')},
            },
        ),
    ]
