# Generated by Django 5.2.3 on 2025-11-21 07:17

import costsheet.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientsetup', '0003_commercialoffer'),
        ('costsheet', '0001_initial'),
        ('salelead', '0006_alter_leadcomment_stage_at_time'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CostSheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('quotation_no', models.CharField(help_text='External quotation / cost sheet number', max_length=50, unique=True)),
                ('date', models.DateField(help_text='Quotation date')),
                ('valid_till', models.DateField()),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('SENT', 'Sent to Customer'), ('ACCEPTED', 'Accepted'), ('REJECTED', 'Rejected'), ('EXPIRED', 'Expired')], default='DRAFT', max_length=16)),
                ('customer_name', models.CharField(max_length=255)),
                ('customer_contact_person', models.CharField(blank=True, max_length=255)),
                ('customer_phone', models.CharField(blank=True, max_length=32)),
                ('customer_email', models.EmailField(blank=True, max_length=254)),
                ('project_name', models.CharField(max_length=255)),
                ('tower_name', models.CharField(blank=True, max_length=255)),
                ('floor_number', models.CharField(blank=True, max_length=50)),
                ('unit_no', models.CharField(blank=True, max_length=50)),
                ('customer_snapshot', models.JSONField(blank=True, null=True)),
                ('unit_snapshot', models.JSONField(blank=True, null=True)),
                ('base_area_sqft', models.DecimalField(blank=True, decimal_places=2, help_text='Area considered for base rate (sq.ft)', max_digits=10, null=True)),
                ('base_rate_psf', models.DecimalField(blank=True, decimal_places=2, help_text='Base rate per sq.ft (from Project / Inventory)', max_digits=12, null=True)),
                ('base_value', models.DecimalField(blank=True, decimal_places=2, help_text='base_area_sqft × base_rate_psf', max_digits=14, null=True)),
                ('discount_percent', models.DecimalField(blank=True, decimal_places=2, help_text='Discount % on base value', max_digits=5, null=True)),
                ('discount_amount', models.DecimalField(blank=True, decimal_places=2, help_text='Discount amount in ₹', max_digits=14, null=True)),
                ('net_base_value', models.DecimalField(blank=True, decimal_places=2, help_text='Base value after discount', max_digits=14, null=True)),
                ('payment_plan_type', models.CharField(choices=[('MASTER', 'Project Plan'), ('CUSTOM', 'Make Your Own')], default='MASTER', max_length=12)),
                ('custom_payment_plan', models.JSONField(blank=True, help_text='Used when payment_plan_type=CUSTOM; full slab structure', null=True)),
                ('gst_percent', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('gst_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('stamp_duty_percent', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('stamp_duty_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('registration_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('legal_fee_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('additional_charges_total', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('offers_total', models.DecimalField(blank=True, decimal_places=2, help_text='Total benefit from offers', max_digits=14, null=True)),
                ('net_payable_amount', models.DecimalField(blank=True, decimal_places=2, help_text='Final figure shown to customer', max_digits=14, null=True)),
                ('terms_and_conditions', models.TextField(blank=True, help_text='Default from CostSheetTemplate / project template')),
                ('notes', models.TextField(blank=True, help_text='Any extra notes per quotation')),
                ('inventory', models.ForeignKey(blank=True, help_text='Inventory snapshot used for this quotation', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cost_sheets', to='clientsetup.inventory')),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cost_sheets', to='salelead.saleslead')),
                ('payment_plan', models.ForeignKey(blank=True, help_text='Used when payment_plan_type=MASTER', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quoted_cost_sheets', to='clientsetup.paymentplan')),
                ('prepared_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cost_sheets_prepared', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cost_sheets', to='clientsetup.project')),
                ('project_template', models.ForeignKey(blank=True, help_text='Project → CostSheetTemplate mapping used for this quotation.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_cost_sheets', to='costsheet.projectcostsheettemplate')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CostSheetAdditionalCharge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=150)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('sort_order', models.PositiveIntegerField(default=1)),
                ('is_taxable', models.BooleanField(default=True, help_text='Part of taxable value or not.')),
                ('costsheet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='additional_charges', to='costsheet.costsheet')),
            ],
            options={
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='CostSheetAppliedOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('applied_amount', models.DecimalField(blank=True, decimal_places=2, help_text='Final discount / benefit applied from this offer', max_digits=14, null=True)),
                ('notes', models.CharField(blank=True, max_length=255)),
                ('costsheet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applied_offers', to='costsheet.costsheet')),
                ('offer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='applied_on_costsheets', to='clientsetup.commercialoffer')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CostSheetAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('label', models.CharField(blank=True, max_length=150)),
                ('file', models.FileField(upload_to=costsheet.models.costsheet_attachment_upload_to)),
                ('doc_type', models.CharField(blank=True, help_text='Optional code: QUOTATION_PDF / SIGNED_COPY / OTHER', max_length=50)),
                ('costsheet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='costsheet.costsheet')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='costsheet',
            index=models.Index(fields=['project', 'status'], name='costsheet_c_project_d6d73a_idx'),
        ),
        migrations.AddIndex(
            model_name='costsheet',
            index=models.Index(fields=['lead'], name='costsheet_c_lead_id_696515_idx'),
        ),
        migrations.AddIndex(
            model_name='costsheet',
            index=models.Index(fields=['date', 'valid_till'], name='costsheet_c_date_c8851b_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='costsheetappliedoffer',
            unique_together={('costsheet', 'offer')},
        ),
    ]
