# Generated by Django 5.2.3 on 2025-11-29 17:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientsetup', '0006_parkinginventory_parkingstatushistory_and_more'),
        ('costsheet', '0002_costsheet_costsheetadditionalcharge_and_more'),
        ('salelead', '0031_alter_salesleadupdate_update_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='costsheet',
            name='lead',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cost_sheets', to='salelead.saleslead'),
        ),
        migrations.AlterField(
            model_name='costsheet',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cost_sheets', to='clientsetup.project'),
        ),
    ]
