# Generated by Django 5.2.3 on 2025-11-30 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('costsheet', '0003_alter_costsheet_lead_alter_costsheet_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='costsheet',
            name='quotation_no',
            field=models.CharField(blank=True, help_text='External quotation / cost sheet number', max_length=50, null=True, unique=True),
        ),
    ]
