# Generated by Django 5.2.3 on 2025-12-02 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('costsheet', '0004_alter_costsheet_quotation_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='costsheettemplate',
            name='development_charges_psf',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, help_text='Development Charges in Amount per Square Feet.', max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='costsheettemplate',
            name='electrical_watern_n_all_charges',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, help_text='psf', max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='costsheettemplate',
            name='provisional_maintenance_psf',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, help_text='psf', max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='costsheettemplate',
            name='share_application_money_membership_fees',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, help_text='money_membership', max_digits=5, null=True),
        ),
    ]
