# Generated by Django 5.2.3 on 2025-12-02 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('costsheet', '0005_costsheettemplate_development_charges_psf_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='costsheettemplate',
            name='electrical_watern_n_all_charges',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, help_text='psf', max_digits=7, null=True),
        ),
    ]
