# Generated by Django 5.2.3 on 2025-12-02 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('costsheet', '0006_alter_costsheettemplate_electrical_watern_n_all_charges'),
    ]

    operations = [
        migrations.AddField(
            model_name='costsheet',
            name='development_charges_amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Development Charges amount.', max_digits=14, null=True),
        ),
        migrations.AddField(
            model_name='costsheet',
            name='electrical_water_piped_gas_charges_amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Electrical, Water & Piped Gas Connection Charges amount.', max_digits=14, null=True),
        ),
        migrations.AddField(
            model_name='costsheet',
            name='legal_compliance_charges_amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Legal & Compliance Charges amount.', max_digits=14, null=True),
        ),
        migrations.AddField(
            model_name='costsheet',
            name='parking_amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Total parking amount = parking_count × per_parking_price.', max_digits=14, null=True),
        ),
        migrations.AddField(
            model_name='costsheet',
            name='parking_count',
            field=models.PositiveIntegerField(blank=True, help_text='Number of parking slots.', null=True),
        ),
        migrations.AddField(
            model_name='costsheet',
            name='per_parking_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Price per parking slot.', max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='costsheet',
            name='possessional_gst_amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='GST amount on possessional charges.', max_digits=14, null=True),
        ),
        migrations.AddField(
            model_name='costsheet',
            name='provisional_maintenance_amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Provisional Maintenance for 6 months amount.', max_digits=14, null=True),
        ),
        migrations.AddField(
            model_name='costsheet',
            name='share_application_money_membership_amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Share Application Money & Membership Fees amount.', max_digits=14, null=True),
        ),
        migrations.AddField(
            model_name='costsheettemplate',
            name='is_possessional_charges',
            field=models.BooleanField(default=False, help_text='If true, template includes possessional charges.'),
        ),
        migrations.AddField(
            model_name='costsheettemplate',
            name='possessional_gst_percent',
            field=models.DecimalField(decimal_places=2, default=0, help_text='GST percentage specifically on possessional charges.', max_digits=5),
        ),
        migrations.AddField(
            model_name='costsheettemplate',
            name='provisional_maintenance_months',
            field=models.PositiveIntegerField(blank=True, default=6, help_text='Number of months for provisional maintenance (e.g. 6).', null=True),
        ),
    ]
