# Generated by Django 5.2.3 on 2025-12-02 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('costsheet', '0007_costsheet_development_charges_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='costsheettemplate',
            name='is_plan_required',
            field=models.BooleanField(default=True, help_text='If false, payment plan selection is optional for this template.'),
        ),
    ]
