# Generated by Django 5.2.3 on 2025-12-02 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('costsheet', '0008_costsheettemplate_is_plan_required'),
    ]

    operations = [
        migrations.AlterField(
            model_name='costsheet',
            name='payment_plan_type',
            field=models.CharField(blank=True, choices=[('MASTER', 'Project Plan'), ('CUSTOM', 'Make Your Own')], default='MASTER', max_length=12, null=True),
        ),
    ]
